jenkinsci/jenkins-test-harness

pom.xml
=> Need to define <repositories> for use on CI

pom.xml
=> Forgot to specify source encoding

pom.xml
Seems to fix an error originally noted in https://github.com/jenkinsci/jenkins/pull/1982. (Appears reproducible only in plugins with dependencies on other plugins, I think.)
@reviewbybees esp. @andresrc
=> Use newer Sisu Inject

pom.xml, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/TestPluginManager.java
Some changes to help with Plugin Wizard (and plugin unbundling) changes for Jenkins 2.0.
=> Plugin wizard helpers

pom.xml, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/MockAuthorizationStrategy.java, src/test/java/org/jvnet/hudson/test/MockAuthorizationStrategyTest.java
Should be self-explanatory. Downstream PRs to come.
@reviewbybees
=> Introduced MockAuthorizationStrategy

pom.xml, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/NoListenerConfiguration.java, src/main/java/org/jvnet/hudson/test/ThreadPoolImpl.java
Test harness now runs with Jetty 9.2
@reviewbybees
=> [JENKINS-23378] Servlet 3.1 support

.gitignore, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
=> Restore a couple of convenience methods

src/main/java/hudson/cli/CLICommandInvoker.java
[JENKINS-32571](https://issues.jenkins-ci.org/browse/JENKINS-32571)
Please review. Thx Pavel
=> [FIXED JENKINS-32571] Preserve original security settings after calling CommandInvoker.invoke()

src/main/java/hudson/cli/CLICommandInvoker.java
This is a follow-up of PR ([#6](https://github.com/jenkinsci/jenkins-test-harness/pull/6)) merged already.
=> [JENKINS-32571] Follow-up & clean-up

src/main/java/org/jvnet/hudson/test/TestPluginManager.java
@jenkinsci/code-reviewers @reviewbybees
=> [FIX JENKINS-34530] Make test harness work for 2.x based plugins

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Replaces https://github.com/jenkinsci/jenkins/pull/1830.
@reviewbybees esp. @jtnord, @kwhetstone
=> Delete JenkinsRule.configRoundtrip(Job) overload

pom.xml
See [JENKINS-35445](https://issues.jenkins-ci.org/browse/JENKINS-35445)
Downstream of https://github.com/andresrc/jenkins-test-harness-htmlunit/pull/1
=> [JENKINS-35445] Custom HtmlUnit Dependency for JTH

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
=> Generalize assertBuildStatus and related methods

src/main/java/org/jvnet/hudson/test/LoggerRule.java
Should be self-explanatory.
@reviewbybees
=> LoggerRule

src/main/java/org/jvnet/hudson/test/MemoryAssert.java
Trying to diagnose the failure of `CpsFlowExecutionTest.loaderReleased` on Jenkins 2, so far unsuccessfully; in the meantime, made various incremental improvements to this test utility.
@reviewbybees
=> Improved version of assertGC

src/main/java/org/jvnet/hudson/test/MemoryAssert.java
Found useful in https://github.com/jenkinsci/workflow-cps-plugin/pull/83.
@reviewbybees
=> Optional mode to track down soft/weak references that delay collection in assertGC

src/main/java/org/jvnet/hudson/test/MemoryAssert.java
Follow-up to #41. Helped in https://github.com/jenkinsci/workflow-cps-plugin/pull/83.
@reviewbybees
=> Finally tracked down a SoftReference leak in java.io.ObjectStreamClass$Caches

src/test/java/org/jvnet/hudson/test/MockAuthorizationStrategyTest.java
=> Demonstrating that MockAuthorizationStrategy by default grants nothing

src/main/java/org/jvnet/hudson/test/MemoryAssert.java
Replaces #41 by actually allowing us to fail the test if `SoftReference`s are leaking.
@reviewbybees
=> Introduced allowSoft parameter to assertGC

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Significantly reduces noise in test output.
@reviewbybees
=> Make Jetty be quiet during functional tests

src/main/java/org/jvnet/hudson/test/TestPluginManager.java
Amends #1. Discussion will be in downstream PR.
@reviewbybees
=> Do not load detached plugins unnecessarily

src/main/java/org/jvnet/hudson/test/FakeChangeLogSCM.java
Needed for https://github.com/jenkinsci/workflow-job-plugin/pull/35 specifically but generally useful, I'd say.
cc @reviewbybees
=> Make FakeChangeLogSCM support Run rather than just AbstractBuild.

src/main/java/org/jvnet/hudson/test/WarExploder.java
[JENKINS-45245](https://issues.jenkins-ci.org/browse/JENKINS-45245)
@reviewbybees
=> [JENKINS-45245] Improve messaging

src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
=> Adding a new RestartableJenkinsRule method comfortable for use with Java 8 test sources

pom.xml, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/RandomlyFails.java, src/main/java/org/jvnet/hudson/test/TestEnvironment.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeoutTest.java
I saw a build of https://github.com/jenkinsci/jenkins/pull/2993 hanging, apparently in `QueueTest`, despite the attempt at a timeout in `JenkinsRule` and decided to try to fix this kind of serious CI problem once and for all.
@reviewbybees
=> JenkinsRule timeout fixes

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Generalizing a trick from https://github.com/jenkinsci/ssh-slaves-plugin/pull/50 & https://github.com/jenkinsci/ssh-slaves-plugin/pull/61.
Before:
```
Running hudson.model.ProjectTest
=== Starting testUnrestrictedJobNoLabelByCloudNoQueue(hudson.model.ProjectTest)
0.046 [id=14]	INFO	o.jvnet.hudson.test.WarExploder#explode: Using jenkins.war resources from …/jenkins/war/target/jenkins
0.282 [id=14]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:45149/jenkins/
0.969 [id=21]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
0.978 [id=21]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2.792 [id=21]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2.793 [id=21]	INFO	jenkins.InitReactorRunner$1#onAttained: …
```
=> Introduced waitOnline, and made createOnlineSlave print more useful diagnostics

src/main/java/org/jvnet/hudson/test/TestExtensionLoader.java
Ameliorates #35.
Before:
```
2.593 [id=21]	WARNING	h.ExtensionFinder$GuiceFinder$SezpozModule#configure: Failed to load hudson.plugins.git.GitSCMTest$SupplySomeEnvVars
java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] org.jvnet.hudson.test.TestExtension.value() (Found data of type class java.lang.String[testEnvironmentVariableExpansion])
at sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:57)
at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:84)
at com.sun.proxy.$Proxy32.value(Unknown Source)
at org.jvnet.hudson.test.TestExtensionLoader.isActive(TestExtensionLoader.java:75)
at …
```
=> Provide friendlier diagnostics when encountering classes compiled against an older version of TestExtension

src/main/java/org/jvnet/hudson/test/MemoryAssert.java, src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
Allowing customization. For example, you can set a custom `timeout`, as in downstream PR (subsequently closed in favor of a different approach).
@reviewbybees
=> Introduce RestartableJenkinsRule.createJenkinsRule

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
=> waitOnline w/ JNLPLauncher failed rather than waiting

src/main/java/org/jvnet/hudson/test/MockQueueItemAuthenticator.java
[JENKINS-47736](https://issues.jenkins-ci.org/browse/JENKINS-47736)
@reviewbybees
=> [JENKINS-47736] Do not even try to persist an Authentication

src/main/java/org/jvnet/hudson/test/LoggerRule.java
From https://github.com/jenkinsci/kubernetes-plugin/pull/244#discussion_r151439605
=> Add LoggerRule.recordPackage

src/main/java/hudson/cli/CLICommandInvoker.java
=> Add methods to get binary output from CLI commands

src/main/java/org/jvnet/hudson/test/RunLoadCounter.java
See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/228. Try
```xml
<jenkins-test-harness.version>2.39-20180604.221735-2</jenkins-test-harness.version> 
```
=> Making RunLoadCounter compatible with Pipeline

src/main/java/org/jvnet/hudson/test/BuildWatcher.java, src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java, src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
=> Making RestartableJenkinsRule also use TemporaryDirectoryAllocator so as to have shorter $JENKINS_HOME paths

.github/release-drafter.yml
Just to save some time on managing changelogs here...
=> Enable Release Drafter for Jenkins Test Harness

src/main/java/jenkins/benchmark/jmh/BenchmarkFinder.java, src/main/java/jenkins/benchmark/jmh/JmhBenchmark.java, src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java, src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Update `@since TODO` in JavaDocs for new methods added in 2.50
=> Update `@since TODO` for benchmark classes in JavaDocs

.dependabot/config.yml
subj. See https://groups.google.com/forum/#!topic/jenkinsci-dev/XMllKuWLO_8 for more context
=> Enable Dependabot in the repository

pom.xml
See https://github.com/jenkinsci/jep/pull/250.
=> [JEP-222] - Add WebSocket support when running Jenkins test rules

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Used in https://github.com/jenkinsci/jenkins/pull/4615. 
With this modification one will be able to customize the context before the test server is started.
=> Add support for customization on the server

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Helpful for diagnosing while a launch is hanging, and just nice to know even when it succeeds.
=> JenkinsRule.waitOnline should stream Computer.logText

src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java, src/main/java/org/jvnet/hudson/test/TestPluginManager.java
followup from #215 to update the javadoc
=> add some javadoc for disabling plugins

src/main/java/com/gargoylesoftware/htmlunit/WebResponseListener.java, src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java, src/main/java/hudson/security/pages/SignupPage.java, src/main/java/org/jvnet/hudson/test/DefaultConstructorChecker.java, src/main/java/org/jvnet/hudson/test/GroovyHudsonTestCase.java, src/main/java/org/jvnet/hudson/test/GroovyJenkinsRule.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/org/jvnet/hudson/test/FlagRuleNoReplacementTest.java, src/test/java/org/jvnet/hudson/test/FlagRuleReplacementTest.java, src/test/java/org/jvnet/hudson/test/MockAuthorizationStrategyTest.java, src/test/java/org/jvnet/hudson/test/recipes/LocalDataTest.java
Addressing review feedback from jenkinsci/jenkins-test-harness#246 plus more minor cleanup along the same lines.
=> Code cleanup

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Added a new method to make it possible to run multiple Jenkins sessions from a test without mixing up HTTP sessions.
=> RealJenkinsRule.withHost

src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java
Replaces the manual `close()` with try-with-resources.
=> Ensure proper stream cleanup

src/main/java/org/jvnet/hudson/test/BuildWatcher.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/MemoryAssert.java, src/main/java/org/jvnet/hudson/test/MockFolder.java, src/main/java/org/jvnet/hudson/test/PluginAutomaticTestBuilder.java, src/main/java/org/jvnet/hudson/test/ResponseCapturingOutput.java, src/main/java/org/jvnet/hudson/test/WorkspaceCopyFileBuilder.java, src/test/java/org/jvnet/hudson/main/AppTest.java
This is a miscellaneous cleanup of deprecation warnings and other TODOs. Each commit message describes the particular change.
=> Miscellaneous code cleanup

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Otherwise we get e.g.
```
java.io.IOException: Cannot run program "C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\bin\java": CreateProcess error=206, The filename or extension is too long
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at org.jvnet.hudson.test.RealJenkinsRule.startJenkins(RealJenkinsRule.java:367)
at …
```
due to the very long `-DRealJenkinsRule.cp=…` argument.
=> Let `RealJenkinsRule` work on Windows

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
See https://github.com/jenkinsci/jenkins/pull/5720.
=> Remove references to `DNSMultiCast.disabled`

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
Matching https://github.com/jenkinsci/jenkins-test-harness/blob/32abb9aca149ad502edcd1e2669a938ee25321a4/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L2857-L2863
=> Remove usages of JNR

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
see [JENKINS-14749](https://issues.jenkins.io/browse/JENKINS-14749)
Depends on https://github.com/jenkinsci/jenkins/pull/6471
=> JENKINS-14749 Update CSS error handler

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
=> `RealJenkinsRule`: Add new flavors of `then` / `runRemotely` allowing to return `Serializable` values

pom.xml
[JENKINS-68890](https://issues.jenkins.io/browse/JENKINS-68890) update htmlunit
downstream of https://github.com/jenkinsci/jenkins-test-harness-htmlunit/pull/70
=> [JENKINS-68890] pick up htmlunit to use the xml api provided by the JDK

Jenkinsfile
Test against the latest weekly.
=> Update weekly version

src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
This pull request fixes either 1.) Temporary Directory Hijacking Vulnerability, or 2.) Temporary Directory Information Disclosure Vulnerability, which existed in this project.
The system temporary directory is shared between all users on most unix-like systems (not MacOS, or Windows). Thus, code interacting with the system temporary directory must be careful about file interactions in this directory, and must ensure that the correct file permissions are set.
This PR was generated because the following chain of calls was detected in this repository in a way that leaves this project vulnerable.
`File.createTempFile(..)` -> `file.delete()` -> either `file.mkdir()` or `file.mkdirs()`.
This vulnerability can have one of two impacts depending upon which vulnerability it is.
1. Temporary …
=> [SECURITY] Fix Temporary Directory Hijacking or Information Disclosure Vulnerability

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Observed this flake:
```
[ERROR] Tests run: 35, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 112.835 s <<< FAILURE! - in hudson.model.ViewTest
[ERROR] hudson.model.ViewTest.shouldNotAllowInconsistentViewName  Time elapsed: 4.426 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "com.gargoylesoftware.htmlunit.html.DomElement.getElementsByTagName(String)" because "doc" is null
at com.gargoylesoftware.htmlunit.html.HtmlPage.executeDeferredScriptsIfNeeded(HtmlPage.java:1498)
at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:282)
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:708)
at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:590)
at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java: …
```
=> Make `JenkinsRule#after` more robust

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
If for some reason the process dies prematurely, it will loop indefinitely.
=> Check for proc liveness

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
=> Use correct logger name in `RealJenkinsRule`

src/main/java/org/jvnet/hudson/test/WarExploder.java
Simpler version of #423. Fixes #551. Tested locally against both Maven and Gradle repository layouts.
=> Support Gradle in `WarExploder#findJenkinsWar`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java, src/main/java/org/jvnet/hudson/test/PrefixedOutputStream.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/main/java/org/jvnet/hudson/test/TailLog.java
Looks nice particularly with `InboundAgentRule`.
=> Support for boldface in `PrefixedOutputStream`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
=> Use `Class.getPackageName`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Simplifying API surface. https://github.com/jenkinsci/jenkins-test-harness/pull/493#discussion_r984468232
(TBH just looking for some stuff to push to `master` to trigger a release, since ci.jenkins.io seems to have lost some webhooks.)
=> Clean up `InboundAgent.Options` & `.Builder`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
https://github.com/jenkinsci/jenkins-test-harness/pull/577#discussion_r1198023319
=> Omit `waitOnline` suggestion from `InboundAgentRule` Javadoc

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Forgotten during the code deletion in #530.
`mvn clean verify -DskipTests`
=> Remove unused `SecureRandom` field

pom.xml
This dependency is managed in the parent POM, so there is no need to declare an explicit version here.
Ran `mvn clean verify -DskipTests`.
=> Use managed Hamcrest version

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Needed for https://github.com/jenkinsci/jenkins/pull/8127.
=> `RealJenkinsRule` copy constructor sharing `home`

.github/renovate.json
Fixes https://github.com/jenkinsci/jenkins-test-harness/issues/626
Tested in my fork https://github.com/timja/jenkins-test-harness/pull/4
```[tasklist]
```
=> Automate updating of Jenkins weekly version

src/main/java/org/jvnet/hudson/test/WarExploder.java
Manually exercised each code path and ensured the message printed was grammatically correct.
=> Improve grammar

src/main/java/org/jvnet/hudson/test/ChannelShutdownListener.java
Otherwise `assertGC` can fail spuriously:
```
private static jenkins.model.Jenkins jenkins.model.Jenkins.theInstance->
hudson.model.Hudson@3aa6e9c0-extensionLists->
java.util.concurrent.ConcurrentHashMap@556eef15-table->
[Ljava.util.concurrent.ConcurrentHashMap$Node;@310f77cc-[35]->
java.util.concurrent.ConcurrentHashMap$Node@1ce52f7d-val->
hudson.ExtensionList@465e7c70-extensions->
java.util.ArrayList@2aaa1e32-elementData->
[Ljava.lang.Object;@f4e4583-[9]->
hudson.ExtensionComponent@59c3ba38-instance->
org.jvnet.hudson.test.ChannelShutdownListener@5aa9f5be-channels->
java.util.ArrayList@37c9353e-elementData->
[Ljava.lang.Object;@64ce5beb-[0]->
hudson.remoting.Channel@3a956eb9-listeners->
java.util.concurrent.CopyOnWriteArrayList@4e97fd41-array->
[Ljava.lang.Object;@1c32e2c5-[0]-> …
```
=> Avoid strong refs from `ChannelShutdownListener`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
In @cloudbees we have a lot of `RealJenkinsRule`-based tests. We often prefer to use method handles for assertions, setup utilities, etc.; this worked for steps which returned values (`Step2`, as of #450) or did not (`Step`) but until now passing a parameter required implementing a `static` class, which is more verbose.
=> `RealJenkinsRule.runRemotely` overloads taking 1–2 step args

pom.xml
Reverts jenkinsci/jenkins-test-harness#681
https://github.com/HtmlUnit/htmlunit/issues/669
=> Revert "Bump org.jenkins-ci.main:jenkins-test-harness-htmlunit from 161.v786c2c610d65 to 162.va_4918b_f36d72"

src/main/java/hudson/cli/CLICommandInvoker.java, src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/MockQueueItemAuthenticator.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/MockAuthorizationStrategyTest.java
https://github.com/jenkinsci/jenkins-test-harness/pull/528 + https://github.com/jenkinsci/jenkins/pull/4848
=> JEP-227 update for JTH

src/main/java/org/htmlunit/html/HtmlFormUtil.java
Fixes #703
Try to find the right Submit button instead of returning whatever `<button>` comes first in the form DOM.
```[tasklist]
```
=> Find the right Submit button

src/main/java/org/htmlunit/html/HtmlFormUtil.java
Makes use of https://github.com/jenkinsci/jenkins/pull/8920
Follows up https://github.com/jenkinsci/jenkins-test-harness/pull/723
```[tasklist]
```
=> Use the marker class to find the form submit button

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
User.Get has a return of CheckForNull yet the returned value is passed
directly as a parameter of a method marked NonNull.
Whilst the return in this case can never be `null` as the create parameter
is `true`, compilers and tools are not clever enough to understand the
human written contract.  so we assert the user in non null before then
passing it down the line, to keep compilers happy
none - just whatever the CI performs.
```[tasklist]
```
=> Fix nullability

pom.xml, src/main/java/org/jvnet/hudson/test/MockFolder.java
Alternative to #731. https://github.com/jenkinsci/cloudbees-folder-plugin/pull/387 should explain the context.
=> Null safety for `createProject`

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
See https://github.com/jenkinsci/winstone/pull/385.
`mvn clean verify -DskipTests`
=> Set server on `WebApplicationContext`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Ensures that even if an inbound agent starts some subprocesses, they are reliably killed off when the test completes.
=> Use `ProcessTree.killAll` from `InboundAgentRule`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Backporting #795 and #802 to the Java 11 branch (`2225.x`).
I have run full PCT suites with these changes without issue.
=> Backport `InboundAgentRule` updates from #795 and #802

pom.xml
As 2.479.1 is the next LTS line.
=> Use 2.479 as baseline

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Backport of #899 on top of the version currently depended by PCT (https://github.com/jenkinsci/plugin-compat-tester/blob/a0e64a0eaa1fd6abc98d3bda8b021d0290c58ea6/src/main/java/org/jenkins/tools/test/hook/Jetty12Hook.java#L31)
=> [JENKINS-75174] Allow webapp context configuration to be discovered via Servlet 3.0 discovery (backport)

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
=> Patch HudsonTestCase for web fragments as well

src/main/java/org/jvnet/hudson/test/junit/jupiter/WithJenkins.java
This adds to `@WithJenkins` Javadoc an example of [JUnit 5 parameterized tests](https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parameterized-tests) using `JenkinsRule`.
=> Add an example of parameterized tests to `@WithJenkins` Javadoc

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
=> `InboundAgentRule.AgentArguments` should not refer to deprecated `*.jnlp`

.git-blame-ignore-revs
=> Update .git-blame-ignore-revs for spotless
