jenkinsci/jenkins-test-harness

src/main/java/org/jvnet/hudson/test/PluginAutomaticTestBuilder.java
In particular, I had a situation where a plugin under test failed to start, which isn't obvious to diagnose in this case
@reviewbybees
=> Actively look for a plugin that failed to start.

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Otherwise the tested Jenkins instance could be accessed from other hosts doing port scanning.
@reviewbybees
=> Listen to connections on localhost only

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
After running this new version of test harness with Jenkins core, I
discovered one issue around the authentication managed by servlet
container.
When Jenkins is configured to delegate authentication to servlet
container, Jetty 8.x used to allow any user, regardless of the roles
they have in Jetty, to qualify. This was because web.xml has the
following and Jetty interpreted '*' to "any role regardless of whether
the role is defined in this web.xml or not"
```
<security-constraint>
<web-resource-collection>
<web-resource-name>Hudson</web-resource-name>
<url-pattern>/loginEntry</url-pattern>
</web-resource-collection>
<auth-constraint>
<role-name>*</role-name>
</auth-constraint>
</security-constraint>
```
Apparently this was one of the ambiguity in the servlet spec, and as of
servlet 3.1, …
=> Jetty 9.2 upgrade follow-up fix

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
Extends https://github.com/jenkinsci/jenkins/pull/1967 to work even on `HudsonTestCase`, which is necessary for `InjectedTest` as [here](https://jenkins.ci.cloudbees.com/job/plugins/job/workflow-plugin/org.jenkins-ci.plugins.workflow$workflow-aggregator/2306/testReport/junit/org.jvnet.hudson.test.junit/FailedTest/org_jvnet_hudson_test_JellyTestSuiteBuilder$JellyTestSuite/):
```
java.nio.channels.ClosedByInterruptException: null
at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1142)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
at …
```
=> [JENKINS-30395] Apply workaround also to HudsonTestCase

pom.xml
If a plugin explicitly declares a dependency on core, war, or some combination of it, but without declaring a dependency to war-for-test, unit tests end up running with one version of the core jar file and another version of the war file. This results in a strange error that's hard to diagnose.
It's very unlikely that plugins using test harness just so happens to be based on 1.580.1, so it's better not to let this module brings in war-for-test, and instead let the caller declare it explicitly, like the plugin parent POM is doing.
=> Make dependency declaration less error prone

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Strip console annotations from output. Helpful in https://github.com/jenkinsci/workflow-cps-plugin/pull/14 for example.
@reviewbybees
=> Better version of JenkinsRule.getLog

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Fixes a regression from #20 observed to affect `ExecutorStepTest.queueTaskVisibility`, which calls `waitForMessage` immediately after `QueueTaskFuture.waitForStart` and thus has a race condition.
@reviewbybees
=> JenkinsRule.getLog should return an empty string if the log file has not yet even been written

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
[JENKINS-36398](https://issues.jenkins-ci.org/browse/JENKINS-36398)
`assertEqualDataBoundBeans` checks only properties defined in the constructor annotated with `DataBoundConstructor`.
It's useful if it also check properties defined with setters annotated with `DataBoundSetter`.
=> [JENKINS-36398] `assertEqualDataBoundBeans` checks also properties defined with `DataBoundSetter`.

src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
1) we are Jenkins :-)
2) put all the files in a directory inside temp rather than directly in
temp.
The problem with using the temporary directory directly is that you can not add
exclusions with wildcards in many anti virus products.  By using a
subdirectory you can add an exclusion to your PATH_TO_TEMP\jenkinsTests.tmp
which will then allow you to exclude jenkinsTests.tmp but still allowing
scanning of your temporary directory (which is desired).
The downside of this is that you will always have a jenkinsTests.tmp directory inside your temp directory - but well the cleanup does not work correctly anyway - so this is nothing new (on windows) - and rather than hundreds of directories you have one directory - which is easier to clean...
@reviewbybees
=> use a subdirectory of the temp directory by default.

src/main/java/org/jvnet/hudson/test/BuildWatcher.java
Needed for https://github.com/jenkinsci/workflow-job-plugin/pull/27, but generally should be an improvement.
@reviewbybees
=> Make fewer assumptions about log handling

src/main/java/org/jvnet/hudson/test/TestExtension.java, src/main/java/org/jvnet/hudson/test/TestExtensionLoader.java, src/test/java/org/jvnet/hudson/test/TestExtensionTest.java
[JENKINS-38304](https://issues.jenkins-ci.org/browse/JENKINS-38304)
This allows make classes annotated with `TestExtension` activate in multiple test cases:
```
public class Test {
@Rule public JenkinsRule j = new JenkinsRule();
@TestExtension({"testForExtension1", "testForExtension2"})
public static class ExtensionForTest extends SomeExtensionPoint {
...
}
@Test
public void testForExtension1() throws Extension {
// ExtensionForTest is available
}
@Test
public void testForExtension2() throws Extension {
// ExtensionForTest is available
}
@Test
public void testForAnotherPoint() throws Extension {
// ExtensionForTest is not available
}
```
=> [JENKINS-38304] Support TestExtension for multiple test cases

src/main/java/org/jvnet/hudson/test/HudsonHomeLoader.java, src/main/java/org/jvnet/hudson/test/recipes/LocalData.java, src/test/java/org/jvnet/hudson/test/recipes/LocalDataTest.java, src/test/resources/org/jvnet/hudson/test/recipes/LocalDataTest/methodData/config.xml
[JENKINS-38306](https://issues.jenkins-ci.org/browse/JENKINS-38306)
It's often the case that I want to use a same local data in multiple test cases,
but not in all test cases in the test.
(e.g. some tests want to use other local data)
This change allows to specify the name of the directory to use
instead of method name
```
public class Test {
@Rule public JenkinsRule j = new JenkinsRule();
@Test
@LocalData("config1")
public void config1_test1() throws Exception {...}
@Test
@LocalData("config1")
public void config1_test2() throws Exception {...}
@Test
@LocalData("config2")
public void config2_test1() throws Exception {...}
@Test
@LocalData("config2")
public void config2_test2() throws Exception {...}
}
```
=> [JENKINS-38306] Add a parameter to LocalData to use instead of method name

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
[JENKINS-38297](https://issues.jenkins-ci.org/browse/JENKINS-38297)
Make `assertEqualsDataBoundBeans` also assert fields annotated with `DataBoundSetter`.
`DataBoundSetter` for fields is introduced since stapler-1.220, stapler/stapler@425314ba247ab90791ca3ba0507ab5b8e25d2a2d
=> [JENKINS-38297] Support DataBoundSetter fields

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Suppresses a warning in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/21. Follows up #37.
@reviewbybees esp. @oleg-nenashev
=> Avoid calling Run.getLogFile merely to check if the file exists

src/main/java/org/jvnet/hudson/test/TestPluginManager.java
@abayer encountered this in IntelliJ. I have in the past in NetBeans, though I am not sure how to reproduce it offhand. IIRC it happens when you have a snapshot test dependency which you have not properly built (`mvn -DskipTests install`)—though I cannot reproduce that at the moment.
@reviewbybees
=> Better report `java.lang.IllegalArgumentException: URI is not hierarchical`

README.md, src/main/resources/org/jvnet/hudson/test/JenkinsComputerConnectorTester/configure.jelly, src/main/resources/org/jvnet/hudson/test/JenkinsComputerConnectorTester/configure_es.properties, src/main/resources/org/jvnet/hudson/test/JenkinsComputerConnectorTester/configure_fr.properties, src/main/resources/org/jvnet/hudson/test/JenkinsComputerConnectorTester/configure_pt.properties, src/main/resources/org/jvnet/hudson/test/JenkinsComputerConnectorTester/configure_pt_BR.properties, src/main/resources/org/jvnet/hudson/test/JenkinsComputerConnectorTester/configure_zh_TW.properties
Copies `configuration.jelly` and associated internationalization properties files from `ComputerConnectorTester` to `JenkinsComputerConnectorTester` so that `JenkinsRule`'s `doConfigRoundTrip(ComputerConnector)` can execute in the same way as `HudsonTestCase` currently does, rather than erroring when attempting to load the `.../configure` URL.
=> [FIXED JENKINS-40351] provide missing config page

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
`JenkinsRule` already imposes a 3m default test timeout unless are running in a debugger, so this timeout is superfluous. It is very annoying to be stepping through something in a debugger only to have the test abruply fail 1m after `waitUntilNoActivity` was called, right before you found the bug!
@reviewbybees
=> Avoid any fixed timeout on waitUntilNoActivity

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
No need to wait for the test to time out.
@reviewbybees
=> waitForMessage can fail immediately if the build is completed

src/main/java/org/jvnet/hudson/test/NoListenerConfiguration.java, src/main/java/org/jvnet/hudson/test/WarExploder.java
Last 2 non-public classes. Blocks ability override `org.jvnet.hudson.test.JenkinsRule#createWebServer`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jenkins-test-harness/46)
=> Make classes public.

src/main/java/hudson/cli/CLICommandInvoker.java
More flexible, and hardly more difficult, to use `MockAuthorizationStrategy` (introduced more recently than `CLICommandInvoker`).
@reviewbybees & @olivergondza
=> Deprecating authorizedTo in favor of a simpler asUser

pom.xml
Currently `9.2.15.v20160210`. Not whatever gets pulled in via jenkins-test-harness-htmlunit, currently `9.2.12.v20150709`. (Does not stop `websocker-{api,client,common}` from being used as of the older version, but probably no one is using these anyway.)
@reviewbybees
=> Pick up jetty-io and jetty-util from our specified version

src/main/java/org/jvnet/hudson/test/TestPluginManager.java
Amends #54. Now that only the existence of `WEB-INF/plugins` (no longer `WEB-INF/detached-plugins`) was checked during a functional test, `the.hpl` and `/test-dependencies/index` were not getting loaded. Discovered in https://github.com/jenkinsci/workflow-job-plugin/pull/44 and reproducible with `-Djenkins.version=2.32.3`.
@reviewbybees
=> Fixed a regression affecting plugin builds

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
It should make issues like https://issues.jenkins-ci.org/browse/JENKINS-37759 much more explicit in functional tests. From what I see there is no valid use-case for proceeding with the test if the initialization fails.
https://issues.jenkins-ci.org/browse/JENKINS-44453
@reviewbybees
=> [FIXED JENKINS-44453] - JenkinsRule should ensure that Jenkins reaches the COMPLETED milestone.

pom.xml
Downstream of https://github.com/jenkinsci/maven-hpi-plugin/pull/65. Supersedes #43.
@reviewbybees
=> [JENKINS-24064] Replace war-for-test classifier with executable-war type

pom.xml, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Critical for [JENKINS-41631](https://issues.jenkins-ci.org/browse/JENKINS-41631) since some of the harder problems relate to random libraries pulled in via the `lib-jenkins-maven-embedder` dependency.
Taking a closer look at the harness code using this library, I could not find any realistic cases where it would actually be used. We already look up test dependencies from the classpath. Furthermore, the group IDs covered are old Hudson names no longer used by Jenkins.
@reviewbybees
=> [JENKINS-41631] Deleting the Maven Embedder dependency from the test harness

pom.xml, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Signed-off-by: olivier lamy <olamy@apache.org>
=> upgrade to jetty 9.4

src/main/java/org/jvnet/hudson/test/LoggerRule.java, src/main/java/org/jvnet/hudson/test/SupportLogFormatter.java
Makes lengthy test output more readable. Useful for example in the test added in https://github.com/jenkinsci/jenkins/pull/3019.
@reviewbybees
=> Make LoggerRule use the nicer formatter developed for support-core

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Without this you can see symptoms of [JENKINS-43666](https://issues.jenkins-ci.org/browse/JENKINS-43666) in certain build environments; observed test failures in a VM claiming (falsely) to have 16 cores (cf. https://github.com/jenkinsci/jenkins/pull/3019#discussion_r138538546). Necessary after #63.
@reviewbybees
=> Use a fixed number of selectors and acceptors regardless of CPU count

src/main/java/org/jvnet/hudson/test/BuildWatcher.java, src/main/java/org/jvnet/hudson/test/SupportLogFormatter.java
Amends #68. Before:
```
=== Starting coalescedQueue(org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerStepTest)
Picking up existing exploded jenkins.war at /…/jenkinsci/pipeline-build-step-plugin/target/jenkins-for-test
2017-09-18 17:29:16.030+0000 [id=15]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:37353/jenkins/
2017-09-18 17:29:16.212+0000 [id=22]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2017-09-18 17:29:21.983+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2017-09-18 17:29:22.040+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2017-09-18 17:29:22.080+0000 [id=22]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2017-09-18 …
```
=> More readable timestamps in log messages during tests

src/main/java/org/jvnet/hudson/test/WarExploder.java
Possible fix of [JENKINS-45245](https://issues.jenkins-ci.org/browse/JENKINS-45245). Not tested with actual IDEA, since I do not use IDEA and would not even know how to set it up to see the problem to begin with. But does the right thing if `"/winstone.jar"` is temporarily mangled to something nonexistent.
@reviewbybees @jenkinsci/code-reviewers
=> [JENKINS-45245] Work around failure of IDEA to add jenkins-war.war to the test CP

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/LoggerRule.java
Corrects a regression in #68 to display `FINE`—`FINEST` messages again; and also improves on it to apply the format to `INFO`+ messages unconditionally.
@reviewbybees
=> Fixing LoggerRule

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Prevents a test error otherwise seen in `docker-commons`.
@reviewbybees
=> Skip optional transitive dependencies

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/SimpleCommandLauncher.java, src/main/resources/org/jvnet/hudson/test/SimpleCommandLauncher/config.jelly
For https://github.com/jenkinsci/jenkins/pull/3076.
@reviewbybees
=> [JENKINS-47393] Remove signature and runtime references to CommandLauncher

pom.xml, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
As requested in [#3129 jenkins-core](https://github.com/jenkinsci/jenkins/pull/3129), some helper methods to ease the use of token (Basic) with username ( password or API Token.
This will allow tests to be written with less code (better readability).
@reviewbybees @jglick
=> Add multiple methods to ease the use of Basic & ApiToken

src/main/java/org/jvnet/hudson/test/LoggerRule.java, src/test/java/org/jvnet/hudson/test/LoggerRuleTest.java
See [JENKINS-47975](https://issues.jenkins-ci.org/browse/JENKINS-47975).
Adds utility methods to `LoggerRule` so that it can be used naturally with `assertThat`. Code taken from @rsandell and `CaptureLogRule` in jenkinsci/ldap-plugin/pull/27.
@reviewbybees
=> [JENKINS-47975] Add utility methods to LoggerRule for matching log entries

src/main/java/org/jvnet/hudson/test/LoggerRule.java
Updates the Javadoc of the `Loggerrule#recorded` methods as requested in #86.
@reviewbybees
=> Update Javadoc for LoggerRule#recorded

src/test/java/org/jvnet/hudson/test/SleepBuilderTest.java
Apparently I forget this class during the split of `jenkins-test-harness`, probably due to it being in Groovy; noticed in the course of https://github.com/jenkinsci/jenkins/pull/3184.
@reviewbybees
=> Moving SleepBuilderTest from core

src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
This can be used to verify that data is appropriately persisted and masters can start cleanly even when normal shutdown-time processes don't get a chance to run. 
Note that it isn't perfect -- slightly-delayed periodic or async processes may still get a chance to run, since the JENKINS_HOME isn't atomically/instantly snapshotted (instead it is copied over a piece at a time).  However, it has been useful to identify persistence issues. 
Deployed as:
* 2.33-20171220.165503-3
@reviewbybees
=> Add utilities to RestartableJenkinsRule to simulate dirty shutdowns

src/main/java/org/jvnet/hudson/test/recipes/PresetData.java
Does nothing you cannot do just as easily with a couple of lines of Java code, and requires the `matrix-auth` plugin to be in the test classpath which is problematic after the split of that plugin from core.
@reviewbybees
=> Deprecating PresetData

src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
[JENKINS-50476](https://issues.jenkins-ci.org/browse/JENKINS-50476)
Used in https://github.com/jenkinsci/jenkins/pull/3364
@reviewbybees
=> [JENKINS-50476] offer a way to assert that Jenkins won't start

pom.xml, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Any test that launches a new java process without passing `-Djava.awt.headless=true` causes focus to switch to the new process, which is mildly infuriating when I want to work on something while running tests in the background. A similar issue was fixed in jenkinsci/plugin-pom#22 to prevent `JenkinsRule` tests from stealing focus by default.
The focus-stealing feature on OS X can be disabled entirely, but it is normally useful and I do not have this issue with any other background processes on my machine, so I'd prefer to fix it here.
I am happy to create a Jira ticket or a screen recording to demonstrate the issue if desired.
@reviewbybees
=> Prevent agent processes from stealing focus on OS X

src/main/java/org/jvnet/hudson/test/NoListenerConfiguration.java
Custom `XXXRule extends JenkinsRule` that overrides `createWebServer` needs public `NoListenerConfiguration` constructor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jenkins-test-harness/104)
=> Follow-up #46

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/recipes/WithTimeout.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeoutTest.java
[JENKINS-49046](https://issues.jenkins-ci.org/browse/JENKINS-49046)
Fixing `JenkinsRule` while keeping the deprecated `HudsonTestCase` as it is.
=> [FIX JENKINS-49046] Fix WithTimeout handling for JenkinsRule

src/main/java/org/jvnet/hudson/test/MockAuthorizationStrategy.java
Follow-up to https://github.com/jenkinsci/remoting/pull/282 from running `com.cloudbees.plugins.credentials.SystemCredentialsProviderTest.given_globalScopeCredential_when_builtAsUserWithoutUseItem_then_credentialNotFound` against a new core. Saw
```
WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class hudson.security.Permission$1 in file:…/jenkins-core-2.138.jar; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
```
which referred to `Permission.ID_COMPARATOR`, that indeed was not designed to be serialized (in this case by XStream).
=> Avoid serializing Permission.ID_COMPARATOR

pom.xml, src/main/java/hudson/slaves/DummyCloudImpl.java
https://issues.jenkins-ci.org/browse/JENKINS-53823
@jenkinsci/sig-platform
=> [JENKINS-53823] - Make DummyCloudImpl compatible with JDK11 + facelift

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
- upstream of https://github.com/jenkinsci/jenkins/pull/3618
- add methods to directly change the throwing exception behavior (and redirect behavior)
- also correct behavior of assertFail that is not taking into account the "throwExceptionOnFailingStatusCode" option
See [JENKINS-53511](https://issues.jenkins-ci.org/browse/JENKINS-53511).
=> [JENKINS-53511] Improve discovery and readability of WebClient

pom.xml, src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
https://github.com/jenkinsci/plugin-pom/pull/122 picks a temp dir root inside the project checkout, so we prefer to keep the relative paths short and sweet.
=> Shortening paths

src/main/java/org/jvnet/hudson/test/TestPluginManager.java
If your plugin has test dependencies, you have a clean checkout (ie,
no `target` directory) and you run the test from JUnit directly (in your IDE),
then you get an obtuse "URI is not hierarchical" message.
Running via the command line using `mvn test` works fine.
This adds an explanatory note to help the user, rather than actually fixing
the issue (as I don't know how to fix it)
Eg, just starting an empty `JenkinsRule` test that depends on `blueocean-rest-impl` tests, I got the following:
```
=== Starting updateWithNonExistentPluginCatalog(com.cloudbees.opscenter.server.bluesteel.cli.TeamCreationRecipesCommandTest)
0.117 [id=14]	INFO	o.jvnet.hudson.test.WarExploder#explode: Exploding C:\Users\Steve\.m2\repository\org\jenkins-ci\main\jenkins-war\2.121.1-cb-1\jenkins-war-2.121.1-cb-1.war …
```
=> Added explanatory text for test failures that contain plugin dependencies

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
@kshultzCB ran into issues with a `JenkinsRule`-based test timing out while inside the debugger. Normally this is not supposed to happen, since it tries to disable the test timeout automatically, but evidently that trick does not work for IDEs (such as IDEA) which do not simply run `mvn` with appropriate arguments but instead launch the test JVM idiosyncratically. Anyway the previous logic would not have worked from Gradle-based plugins etc. @MarkEWaite alerted me to a standard utility he had used in https://github.com/jenkinsci/git-client-plugin/commit/cb6e220ff6359120974a41cb1f8e43ea3226883f which does the job better.
=> Use DisableOnDebug’s logic rather than rolling our own

src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
This is an idea I got after reporting [JENKINS-48264](https://issues.jenkins-ci.org/browse/JENKINS-48264), which is a recent regression in pipeline-maven-plugin with job names (hence workspace paths) containing space characters.  
It's not the first time I come across a quoting issue like that in a plugin, so... why not try to detect them (at least some) sooner, by tweaking JenkinsRule to always put some space characters in workspaces paths?
My initial thought was to make a WorkspaceLocator or something like that, but the patch in this PR is even simpler.
I've verified that it somehow works: it breaks 6 out of 27 tests in the WithMavenStepOnMasterTest class in pipeline-maven-plugin 3.0.3.
I'm not sure how good or stupid this idea is, just wanted to share and get your feedback.
=> [RFC] space char in tmp dirs to catch quoting issues

src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
Clutters command line output without benefit to the consumer
=> Don't report temporary dir name to System.err

README.md, pom.xml
This is the follow-up after #89 and jenkinsci/jenkins-test-harness-htmlunit#4.
=> bump JTH-htmlunit to 2.31-2

pom.xml, src/main/java/org/jvnet/hudson/test/MemoryAssert.java
cc @jenkinsci/java11-support 
To be used for https://github.com/jenkinsci/workflow-job-plugin/blob/72eecff5f7bd98aa4e73368c31203c50b3e89149/src/test/java/org/jenkinsci/plugins/workflow/job/MemoryCleanupTest.java#L35 fix on Java 11. Fix upcoming.
=> Disable assertion on Java 9+

pom.xml, src/main/java/org/jvnet/hudson/test/MemoryAssert.java
Amends #126 to avoid the need to pick up https://github.com/jenkinsci/lib-version-number/pull/11. See https://github.com/jenkinsci/plugin-pom/pull/175#issuecomment-478644544.
=> Drop dependency on JavaSpecificationVersion introduced in version-number 1.6, newer than our core baseline

pom.xml, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/LoggerRule.java
Developed during JEP-210 work but could be broadly useful.
=> Added JenkinsRule.showAgentLogs utility

.mvn/extensions.xml, .mvn/maven.config, Jenkinsfile, pom.xml
Inspired by https://github.com/jenkinsci/swarm-plugin/pull/81#discussion_r279812868.
=> Incrementalified

src/main/java/org/jvnet/hudson/test/MemoryAssert.java
Useful working on the likes of https://github.com/jenkinsci/workflow-cps-plugin/pull/289.
=> Always print softErr from MemoryAssert even if test ultimately passes

src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java, src/test/java/org/jvnet/hudson/test/JenkinsMatchersTest.java
I noticed while reviewing https://github.com/jenkinsci/configuration-as-code-plugin/pull/862 that it'd be nice to have matchers for Secret. I also added one for regular expressions as Hamcrest doesn't come with one by default despite being rather generic.
@reviewbybees
=> Add Hamcrest matchers for Secret and Pattern

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RestartableJenkinsRuleTest.java
Inspired by [jenkinsci/swarm-plugin#81 (comment)](https://github.com/jenkinsci/swarm-plugin/pull/81#discussion_r279723719). Testing the Swarm client requires having Jenkins run on the same port before and after restart (c.f. jenkinsci/swarm-plugin#81). Here we add this functionality to `RestartableJenkinsRule`. The new functionality is opt-in to preserve existing behavior for tests which don't need it and which could be negatively impacted by races for open ports.
=> Allow port reuse in RestartableJenkinsRule

pom.xml
Updated the parent POM to [the latest version](https://github.com/jenkinsci/pom/releases), which has SpotBugs support, and migrated the annotations dependency from FindBugs to SpotBugs.
=> Switch code annotations to the SpotBugs library

src/main/java/org/jvnet/hudson/test/LoggerRule.java
`LoggerRule` has two basic functions:
* Let you see `FINE` or lower messages from particular loggers in test output. (`record`)
* Keep track of messages so you can assert things about them. (`capture`)
For the `record` aspect, there was an unfortunate side effect that messages to those loggers at `INFO` or above got printed once for the general system logger (formatted nicely by `JenkinsRule`), _plus_ once per matching `LoggerRule`. So the test output would get multiple copies of lots of messages, which was harmless but irritating.
Not trivially testable, but tried it interactively in https://github.com/jenkinsci/kubernetes-plugin/pull/503 and it seemed to do the job.
=> Avoid printing duplicated messages when LoggerRule is used

pom.xml, src/main/java/jenkins/benchmark/jmh/BenchmarkFinder.java, src/main/java/jenkins/benchmark/jmh/JmhBenchmark.java, src/test/java/jenkins/benchmark/jmh/BenchmarkTest.java
Reflections was causing a dependency conflict with the Guava from
Jenkins Core (see: https://travis-ci.org/jenkinsci/configuration-as-code-plugin/jobs/546110907#L878)
@jenkinsci/gsoc2019-role-strategy
=> [JENKINS-58038] Use Annotation-Indexer instead of Reflections

README.md
Just a minor change, similar to patches in other repositories. Will merge once the build passes and then ship the new release
=> Move changelogs to GitHub releases

src/main/java/org/jvnet/hudson/test/LoggerRule.java
#138 rendered `record` useless as it no longer displayed any messages at `FINE` or below. Not sure how I did not notice this before, but anyway observed in https://github.com/jenkinsci/kubernetes-plugin/pull/522. I do not have a fix for the original (duplication) problem handy, so I am just backing out the bad fix.
=> Reverting #138 as it broke display of FINE- messages

src/main/java/org/jvnet/hudson/test/LoggerRule.java, src/test/java/org/jvnet/hudson/test/LoggerRuleTest.java
Causing flakes in https://github.com/jenkinsci/kubernetes-plugin/pull/525
> java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at org.csanchez.jenkins.plugins.kubernetes.pipeline.KubernetesPipelineTest.runInPod(KubernetesPipelineTest.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveC …
=> Fix concurrent access to LoggerRule#getMessages

src/main/java/org/jvnet/hudson/test/TestPluginManager.java
While `TestHplMojo` creates `target/test-classes/the.hpl`, when we are actually setting up a plugin directory we should be copying this to a filename which reflects this plugin’s identifier. Useful in conjunction with https://github.com/jenkinsci/jenkins/pull/4100.
=> [JENKINS-58362] Create ${TestPluginManager.rootDir}/${artifactId}.jpl, not the.jpl

src/main/java/org/jvnet/hudson/test/MemoryAssert.java
While perusing the source tree, I noticed some deprecated methods:
- The documentation for [`edu.umd.cs.findbugs.annotations.SuppressWarnings`](http://findbugs.sourceforge.net/api/edu/umd/cs/findbugs/annotations/SuppressWarnings.html) states: "Was used to suppress FindBugs warnings but generates name conflicts with `SuppressWarnings`".
Accordingly, I replace any usages of `edu.umd.cs.findbugs.annotations.SuppressWarnings` with usages of `edu.umd.cs.findbugs.annotations.SuppressFBWarnings`.
=> Remove usages of deprecated `@SuppressWarnings ` references

pom.xml
`pom.xml` currently has the `enforcer.skip` property set to `true`. This completely disables the Enforcer checks, which hides useful warnings. Unfortunately, re-enabling the Enforcer checks reveals this `RequireUpperBoundDeps` warning:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (display-info) @ jenkins-test-harness ---
[WARNING] Rule 3: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.guava:guava:11.0.1 paths to dependency are:
+-org.jenkins-ci.main:jenkins-test-harness:2.54-SNAPSHOT
+-org.jenkins-ci.main:jenkins-war:2.60.3
+-org.jenkins-ci.main:jenkins-core:2.60.3
+-com.google.guava:guava:11.0.1
and …
```
=> Enable Maven Enforcer checks

src/main/java/org/jvnet/hudson/test/DeltaSupportLogFormatter.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
While trying to use my new utility from #127, I kept on missing remote log messages, even (randomly) in the original use case of `FileLogStorageTest`. At first I suspected that https://github.com/jenkinsci/jenkins/pull/3961 was to blame, and indeed a `flush` call might be necessary, but I was running on an older core prior to this patch! Finally I recalled that `Logger` can be garbage-collected and your customizations lost. With this patch, I am getting messages reliably at last.
=> Fixing showAgentLogs

pom.xml
The dependency on `ant-launcher` was added in [JENKINS-11416](https://issues.jenkins-ci.org/browse/JENKINS-11416) in 2011 to work around a user-reported build issue. The user's Ant POM was missing the `ant-launcher` dependency. The [official Ant POM](https://search.maven.org/remotecontent?filepath=org/apache/ant/ant/1.10.6/ant-1.10.6.pom) declares this dependency, so it's unclear why the user was missing the dependency. In any case, it seems unlikely this workaround is still needed 8 years later (and even if it is, it would be easy to restore). Keeping this workaround in the source tree results in undesirable noise such as jenkinsci/jenkins-test-harness#152. It would be simpler to just remove the unnecessary dependency declaration.
=> Remove unnecessary dependency on ant-launcher

pom.xml, src/main/java/org/jvnet/hudson/test/MockFolder.java
I need this modification to be able to merge this PR: https://github.com/jenkinsci/jenkins/pull/4122
Test are failing there because the default value for isNameEditable is false, and the PR add a protection when trying to rename a Item with isNameEditable false. MockFolder used in test does not override isNameEditable to true but it should.
The isNameEditable method is available only on jenkins-core > 2.110, so I upgrade jenkins-war to the first version including this method.
=> [JENKINS-58571] Fix default value for `isNameEditable()` on MockFolder.

pom.xml
Inspired by [jenkinsci/jenkins-test-harness#156 (comment)](https://github.com/jenkinsci/jenkins-test-harness/pull/156#pullrequestreview-267614033). Supersedes jenkinsci/jenkins-test-harness#156. This repository currently uses the GMavenPlugin to run a `package.groovy` to zip a few files during the build. The GMaven plugin is no longer maintained; active development is now taking place in the GMavenPlus project. Therefore, we switch to GMavenPlus.
After updating the group ID, artifact ID, and version, I got this error:
```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.7.1:execute (preset-packager) on project jenkins-test-harness: The parameters 'scripts' for goal org.codehaus.gmavenplus:gmavenplus-plugin:1.7.1:execute are missing or invalid -> [Help 1]
``` …
=> Switch from GMaven to GMavenPlus

Jenkinsfile
Simplification of #131. Also switching to ACI.
=> prepareToPublishIncrementals

pom.xml
This change supersedes #151.   
While no api changes have occurred since 1.3, packaging has changed.
The core and library jars are now empty, but still needed to force JUnit and other consumers to use the newer versions.
Closes #151 
@oleg-nenashev @jglick
=> Bump hamcrest-library from 1.3 to 2.1

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
This commit is excepted to reveal bogus tests that do not properly shutdown,
especially on Windows where directory cannot be removed if there are any running processes that use it as a working directory.
=> Stop swallowing exceptions that happen in `TestEnvironment#dispose()`

src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
#66 added a `Step` interface with a comment stating: "TODO Java 8: `@FunctionalInterface`". The Java level was set to 8 in #63, so this TODO can now be completed.
=> Add FunctionalInterface annotation to RestartableJenkinsRule.Step

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
This is identical to JenkinsRule.buildAndAssertSuccess but with user-specified build status
=> Introduce new `JenkinsRule#buildAndAssertStatus()` method

pom.xml
#155  continuation
https://mvnrepository.com/artifact/org.netbeans.modules/org-netbeans-insane/RELEASE802 is Date | (Nov 26, 2014) and it's placed in weird rpeo
Note `New Version | RELEASE111`
is (Aug 07, 2019) and it's in central repo!
@jglick what does netbeans do with all this versions and repos?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/jenkins-test-harness/169)
=> Update org-netbeans-insane from RELEASE802 to RELEASE111

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Just noticed that #80 was overly specific: there is already an API method for inbound vs. outbound launchers.
=> Update `JenkinsRule#waitOnline()` to wait for all launchable agents, not just for `JNLPLauncher` implementations

pom.xml, src/main/java/com/gargoylesoftware/htmlunit/WebClientUtil.java, src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java
diff https://github.com/HtmlUnit/htmlunit/compare/HtmlUnit-2.31...2.36.0
=> Upgrade htmlunit to 2.36.0

src/main/java/org/jvnet/hudson/test/FakeChangeLogSCM.java
It's useful in tests to have the full functionality.
The default implementation in the abstract parent class just throws an `UnsupportedOperationException`.
=> Add implementation for getAffectedFiles to FakeChangeLogSCM#EntryImpl

pom.xml
Should integrate #178 and #176
=> Update Java Microbenchmark Harness to 1.22, use a single property to manage dependencies

src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
Due to [JENKINS-60308](https://issues.jenkins-ci.org/browse/JENKINS-60308) if a test using `JenkinsRule` can not clean up you get a CompositeIOException which would be caught and rethrown but the details of why would be missing.  Locally (so long as the files are not deleted in a JVM shutdown hook you can look in the directory locally to see what could not be deleted, but when run on a CI server you do not have this luxury.
since #166 this causes the build to fail - yet there is no diagnostics to help you determine why (and the majority of devs are not on windows, or have access to windows).
So let us be helpful by not wrapping the Exception which won't work all the times but will for the vast majority of cases.
The real fix would be in Jenkins itself - this is just a temporary …
=> workaround JENKINS-60308 by not wrapping the IOException

pom.xml, src/test/java/org/jvnet/hudson/test/TestCrumbIssuerConfigurationAsCodeTest.java
Now that Jenkins 2.60.3 is used, this test can be added. It was originally provided already as #120 to test #119 but could not be merged at that time due to the dependency on a newer Jenkins version.
=> [JENKINS-55381] Add test for TestCrumbIssuer compatibility with JCasC

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java
I think this fixes [JENKINS-60694](https://issues.jenkins-ci.org/browse/JENKINS-60694). Just copies the fix from #69 to `HudsonTestCase` which I should have done to begin with.
=> [JENKINS-60694] Do not use defaults for acceptors & selectors

src/main/java/org/jvnet/hudson/test/ChannelShutdownListener.java
Has happened multiple times especially prior to https://github.com/jenkinsci/maven-hpi-plugin/pull/140 that `ChannelShutdownListener` is found in customer heap dumps, apparently due to mispackaged plugins. This can lead to memory leaks as every `Channel` ever created (and all of its `ExportTable`s etc.) gets held onto.
This should warn about it, and make it clear where the culprit is, such as `/var/lib/jenkins/plugins/xray-for-jira-connector/WEB-INF/lib/jenkins-test-harness-2.13.jar` from [XRAYJENKINS-55](https://jira.xpand-it.com/browse/XRAYJENKINS-55).
=> [JENKINS-58771] Warn if ChannelShutdownListener loaded outside of a test context

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
[JENKINS-60821](https://issues.jenkins-ci.org/browse/JENKINS-60821)
Jetty knows better than us, so let Jetty configure its own defaults for the ThreadPool (min 8 max 200) and #acceptor/selector threads.
This applies feedback from eclipse/jetty.project#4492
Whilst we are here - give all of the Jetty Thread pools different names so it is obvious which pool is which
=> [JENKINS-60821] let Jetty configure its own defaults

pom.xml
I doubt dependabot can resolve variables in the URL as it reading XML directly instead of parsing variables.
=> Add the GitHub repo URLs to the Maven metadata

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
[JENKINS-61031](https://issues.jenkins-ci.org/browse/JENKINS-61031)
- JenkinsRule#assertAllImageLoadSuccessfully no longer breaks when download images on the format `<img src="/example.svg" />`
- Refactored and added a JenkinsRule#assertImageLoadsSuccessfully to implement the same test but for single images
@timja 
@fcojfernandez 
I have change the way of testing whether images were download to just check for the status code. That way it's format-agnostic.
I appreciate suggestions for how to add unit tests for this one.
=> [JENKINS-61031] Fixed download of SVG images

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
If this property is set and if the changes in jenkinscis/jenkins#4389 are active, then this changes the default behavior to show full stack traces. (It enables stack traces.) If the property isn't set with 4389 then stack traces are suppressed and some tests that check error results fail. If the property is set without 4389 then it's a no-op.
This matches other existing behavior. See the nearby line for allowing Dispatcher tracing, `Dispatcher.TRACE`.
It makes testing and troubleshooting a little easier.
=> [JENKINS-60410] Disable stack trace suppression for tests.

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
I think this is the root of many of the flakes surrounding `WorkflowRun.finish`, like https://github.com/jenkinsci/workflow-job-plugin/pull/158. For both traditional job types (https://github.com/jenkinsci/jenkins/blob/449c5aced523a6e66fe3d6a804e5dbfd5c5c67c6/core/src/main/java/hudson/model/Run.java#L520-L537) and Pipeline (https://github.com/jenkinsci/workflow-job-plugin/blob/5323c277aaa1194f899e8e320bb7246f2bbcc24f/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java#L778-L779), `!Run.logUpdated` is stronger than `!Run.building`, so we ought to wait for the build to _really_ be completed.
=> waitForCompletion should wait for !Run.logUpdated even after !Run.building

src/main/java/org/jvnet/hudson/test/recipes/WithTimeout.java
Useful during debugging to avoid writing:
```
{j.timeout = 0;}
```
Nothing depends on this improvement :)
=> Add WithTimeout support for JUnit4

pom.xml, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Looks like https://github.com/jenkinsci/jenkins/pull/2864 and https://github.com/jenkinsci/jenkins-test-harness/pull/167 don't work well together.
Untested.
=> Make this compile again with a Jenkins 2.61+ dependency

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/recipes/WithTimeout.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeoutTest.java
It was already implemented directly in JenkinsRule, private method: getTestTimeoutOverride
I updated a test case that was not asserting something useful.
Revert #209 + update test.
@jglick @MarkEWaite as reviewers of the first one
=> Revert the change with WithTimeout

src/main/java/org/jvnet/hudson/test/JenkinsSessionRule.java
This has been on my to-do list for years. There is a bunch of complex stuff in `RestartableJenkinsRule` that is rarely needed, like support for dirty shutdowns (used only for testing some edge cases in Pipeline) and custom port selection (used by the `kubernetes` plugin IIRC), but the immediate motivation was to run `then` blocks synchronously. The batching behavior in `RestartableJenkinsRule` is rather counterintuitive, seems unnecessary, and mystifyingly breaks basic JUnit stuff like `@After` methods.
Also this variant preserves the port across runs. All in all, should be a drop-in replacement for most uses.
=> Added JenkinsSessionRule

src/main/java/org/jvnet/hudson/test/BuildWatcher.java
Otherwise when using `RestartableJenkinsRule` you can get log spam such as
```
…
13.076 [id=1]	INFO	jenkins.model.Jenkins#cleanUp: Jenkins stopped
Test timeout disabled.
=== Starting …
0.012 [id=1]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:33923/jenkins/
0.153 [id=15]	SEVERE	h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (watching builds/15) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.AssertionError: class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject is missing its descriptor
at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1600)
at …
```
=> BuildWatcher should ignore any Throwable when Jenkins is not up

src/main/java/org/jvnet/hudson/test/ExtractResourceWithChangesSCM.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/SingleFileSCM.java, src/main/java/org/jvnet/hudson/test/TestBuilder.java, src/main/java/org/jvnet/hudson/test/TestNotifier.java
https://github.com/jenkinsci/jenkins/pull/4944 needs compatibility with https://github.com/x-stream/xstream/commit/4f5ea0915d77467e73f3968f3217569b9c012183: [XSTR-762](https://x-stream.github.io/jira/762/)
=> writeReplace should be protected when intended for use from subtypes

src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
This PR deprecates the methods in `RestartableJenkinsRule` that require anonymous classes.
In general, we prefer the `then*` methods as they support lambda expressions, which improves readability of tests. New contributors to old test suites often add new uses of `addStep` and similar methods because that is what the existing code does (it was created before Java 8), and there is nothing that indicates that `then` should be used instead.
=> Deprecate RestartableJenkinsRule.addStep* and update Javadoc

src/main/java/org/jvnet/hudson/test/FlagRule.java, src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java, src/test/java/org/jvnet/hudson/test/FlagRuleNoReplacementTest.java, src/test/java/org/jvnet/hudson/test/FlagRuleReplacementTest.java, src/test/java/org/jvnet/hudson/test/FlagRuleSystemPropertyTest.java, src/test/java/org/jvnet/hudson/test/FlagRuleTest.java
A lot of Jenkins tests turn on some hidden flag defined by static variable, so it would be convenient to not need `@Before` & `@After` methods for this common idiom.
=> Added FlagRule

pom.xml, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/ResponseCapturingOutput.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Proposal after discussion with Jesse.
Increase the core requirement to have at least the first LTS with the new API token system.
(Manually tested with 2.260 to ensure compatibility of the "else")
=> Auto-creation of API Token when using withBasicApiToken

src/main/java/org/jvnet/hudson/test/LoggerRule.java
* Don't duplicate records with level `INFO` or above
* `quiet()` allows to record log messages but not print them to console. Useful if there are multiple LoggerRule instances.
=> LoggerRule improvements

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Looks like core reorganized CSS stuff without adapting the test harness accordingly, resulting in unnecessary log spam in plugin tests using `JenkinsRule.WebClient`.
FYI @timja @fqueiruga 
```
0.093 [id=16]	INFO	o.jvnet.hudson.test.WarExploder#explode: Picking up existing exploded jenkins.war at /Users/danielbeck/Repositories/github.com/daniel-beck/matrix-auth-plugin/target/jenkins-for-test
0.381 [id=16]	INFO	o.jvnet.hudson.test.JenkinsRule#createWebServer: Running on http://localhost:57024/jenkins/
0.663 [id=30]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
0.930 [id=41]	INFO	hudson.PluginManager#considerDetachedPlugin: Loading a detached plugin as a dependency: /var/folders/sc/wj54hsn531l4lnbnqwthds_00000gn/T/jenkins13091184227555156879/plugins/command-launcher.jpi …
```
=> Suppress more core CSS warnings

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Otherwise if you are using e.g.
```java
r.jenkins.setSecurityRealm(r.createDummySecurityRealm());
```
you have to add a superfluous
```java
User.getById("admin", true);
```
before calling
```java
r.createWebClient().withBasicApiToken("admin");
```
=> withBasicApiToken should create the user as needed

.github/dependabot.yml, .github/release-drafter.yml, .github/workflows/cd.yaml, .mvn/extensions.xml, .mvn/maven.config, pom.xml
As per https://github.com/jenkinsci/incrementals-tools/#superseding-maven-releases. Requires https://github.com/jenkins-infra/repository-permissions-updater/pull/1846.
=> [JEP-229] Enable CD

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
If an IDE’s test runner offers a snapshot plugin dependency in the test classpath as `…/target/classes/` then load its `…/target/test-classes/the.hpl` just like we would the plugin under test. (This already worked for `JenkinsRule`.) Tested with NetBeans; not sure if this works nicely on IDEA, VSCode, Eclipse, etc.
=> Support plugin-to-plugin snapshot dependencies

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
- Call `stopJenkins` automatically
- Ability to disable plugins
- Ability to add Java options
- Apply an overall timeout, and print diagnostics if Jenkins cannot be contacted or the test hangs
=> RealJenkinsRule improvements

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Seems to have been a flake somewhere, but the root cause was perhaps concealed by a secondary mistake in error handling:
```
java.lang.NullPointerException
at java.io.Reader.<init>(Reader.java:78)
at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
at org.apache.commons.io.IOUtils.copy(IOUtils.java:921)
at org.apache.commons.io.IOUtils.toString(IOUtils.java:2681)
at org.apache.commons.io.IOUtils.toString(IOUtils.java:2661)
at org.jvnet.hudson.test.RealJenkinsRule.startJenkins(RealJenkinsRule.java:365)
at …
```
=> NPE observed in RealJenkinsRule.startJenkins

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Observed a build in CI that was blocked with the following stack
```
"main" #1 prio=5 os_prio=0 cpu=6449.46ms elapsed=2937.07s tid=0x00007f869c011000 nid=0x236 in Object.wait()  [0x00007f86a3394000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(java.base@11.0.1/Native Method)
- waiting on <no object reference available>
at java.lang.Object.wait(java.base@11.0.1/Object.java:328)
at java.lang.ProcessImpl.waitFor(java.base@11.0.1/ProcessImpl.java:495)
- waiting to re-lock in wait() <0x00000000943c10b0> (a java.lang.ProcessImpl)
at org.jvnet.hudson.test.RealJenkinsRule.then(RealJenkinsRule.java:243)
at io.jenkins.plugins.artifact_manager_jclouds.s3.MinioIntegrationTest.artifactArchiveAndDelete(MinioIntegrationTest.java:175)
```
The Jenkins stack showed jetty …
=> RealJenkinsRule: wait for max 60 seconds for Jenkins to terminate

src/main/java/hudson/cli/CLICommandInvoker.java
Ought to also support registration via `@OptionalExtension` from the `variant` plugin.
=> CLICommandInvoker was being too strict about how a CLICommand was registered

src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RestartableJenkinsRuleTest.java
The FileTreeWalker is quite a bit less hardened that one might hope.
The visitor must handle a NoSuchFileException throw during copy, but
the `visitFileFailed` method must handle NoSuchFileException if thrown
by the walker.
https://issues.jenkins.io/browse/JENKINS-65068
@jtnord @olamy
=> [JENKINS-65068] `RestartableJenkinsRule`: Handle `NoSuchFileException` thrown from `FileTreeWalker`

pom.xml, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout1Test.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout2Test.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout3Test.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout4Test.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout5Test.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout6Test.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeout7Test.java, src/test/java/org/jvnet/hudson/main/JenkinsRuleTimeoutTestBase.java
See https://github.com/jenkinsci/jenkins-test-harness/pull/303#issuecomment-831811098. By running against an instrumented version of core, the root problem seems to be that `FailOnTimeout` does its interruption in a separate thread, so it is unpredictable when `Jenkins.cleanUp` will be called—sometimes _after_ another test has started `Jenkins.<init>`. `cleanUp` does supposedly verify that it is cleaning up `this`, and `JenkinsRule` has an additional defense, but it seems there are lots of race conditions here. Safest to run each of these tests in its own JVM. We do not really care about a test that failed due to timeout also “poisoning” other tests in the same JVM since we expect the test suite to fail at that point anyway, so this probably only affects `JenkinsRuleTimeoutTest` itself.
=> `JenkinsRuleTimeoutTest` was flaky

pom.xml, src/main/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleExtension.java, src/main/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleResolver.java, src/test/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleResolverTest.java, src/test/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleResolverWithMethodScopeTest.java
Provides JUnit 5 support for `JenkinsRule` as discussed in [JENKINS-48466](https://issues.jenkins.io/browse/JENKINS-48466).
Tests written with JUnit 5 don't support rules, thus require code like this to work with the test harness.
```java
// JUnit 5
@ExtendWith(JenkinsRuleResolver.class)
class ExampleJUnit5Test {
@Test
public void example(JenkinsRuleExtension r) {
// use 'r' as usual
// ...
}
}
```
/cc @uhafner
=> [JENKINS-48466] JenkinsRule support for JUnit 5

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Otherwise `configRoundtrip` on a default view fails (cryptically) because it goes to `http://localhost:8080/jenkins/configure` and does not find a form `viewConfig`.
=> `WebClient.getPage(View, String)` needed to use `getViewUrl` not `getUrl`

src/main/java/hudson/cli/CLICommandInvoker.java
This method was deprecated in #53 but was still used at least in core and complicated https://github.com/jenkinsci/jenkins/pull/5605.
=> Stop `CLICommandInvoker.authorizedTo` from trying to serialize `Permission`s

pom.xml, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
This field has been [unused since 1.527](https://github.com/jenkinsci/jenkins/commit/47de54d070f67af95b4fefb6d006a72bb31a5cb8). Setting it is pointless. Stop doing so, so that one day we might be able to actually remove it.
=> Stop setting `useAntClassLoader` which nothing consumes

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Plan to use this in a proprietary test, but seems broadly useful.
=> Allow environment variables to be defined on Jenkins process

src/main/java/org/jvnet/hudson/test/IOUtil.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
[JENKINS-67086](https://issues.jenkins.io/browse/JENKINS-67086)
When running tests in parallel I sometimes see port conflicts
```
java.io.IOException: Failed to start Jetty
at winstone.Launcher.<init>(Launcher.java:194)
at winstone.Launcher.main(Launcher.java:369)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at Main._main(Main.java:375)
at Main.main(Main.java:151)
Caused by: java.io.IOException: Failed to bind to /127.0.0.1:50786
at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
at …
```
=> [JENKINS-67086] Ensure a free port is used by RealJenkinsRule

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Updated the link to documentation in Javadoc to point to `www.jenkins.io/doc/developer/` instead of the now defunct `wiki.jenkins-ci.org/display/JENKINS/Unit+Test`
=> update documentation link in Javadoc

src/main/java/org/jvnet/hudson/test/JenkinsSessionRule.java
Analogous to `RealJenkinsRule.getHome`, which was added in #352. Useful in cases where you want to modify something in `JENKINS_HOME` between Jenkins restarts.
Once the CI build completes I will update https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/185 to consume the new method.
=> Add new JenkinsSessionRule.getHome method

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
We run `System.gc()` after shutting down Jenkins and deleting the Jenkins home directory, but by then it is too late on Windows: deleting the Jenkins home directory may have already failed due to open files held by class loaders. This PR solves the problem by moving the GC to before we delete the Jenkins home directory.
=> GC before trying to delete the Jenkins home directory

src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java, src/main/java/org/jvnet/hudson/test/HudsonHomeLoader.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/WarExploder.java, src/main/java/org/jvnet/hudson/test/recipes/LocalData.java
Javadoc generation on Java 11 and later throws errors without this PR.
=> Use `{@code}` rather than `<tt>`

src/main/java/org/jvnet/hudson/test/BuildWatcher.java
Known for a long time but reminded when working on https://github.com/jenkinsci/pipeline-input-step-plugin/pull/69#issuecomment-1004904008: if you use `@LocalData` to test resumption of a Pipeline build, and are using `BuildWatcher`, without this patch you will get a confusing warning and no log output.
=> Make `BuildWatcher` behave better with `@LocalData`

src/main/java/org/jvnet/hudson/test/JellyTestSuiteBuilder.java
As of https://github.com/jenkinsci/jenkins/pull/5923 `f:radio` uses `for=` to attach labels by generating a unique ID per input.
[Theme manager](https://github.com/jenkinsci/theme-manager-plugin/pull/75) is using a similar (completely safe) method.
Can we remove this test please given core is using this pattern?
One of the annoying parts of `InjectedTest` is you can't selectively disable it -.-
=> Remove unneeded injected test

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Fixes the following SpotBugs violation:
```
[ERROR] High: Random object created and used only once in org.jvnet.hudson.test.JenkinsRule.generateNewApiTokenValue() [org.jvnet.hudson.test.JenkinsRule] At JenkinsRule.java:[line 1146] DMI_RANDOM_USED_ONLY_ONCE
```
=> Fix `DMI_RANDOM_USED_ONLY_ONCE` SpotBugs violation

pom.xml, src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
Reverts #397 and adds test coverage for `MemoryAssert#assertGC`. The new test fails without the revert of #397 and passes with the revert of #397.
Fixes #360
=> Restore working version of `MemoryAssert#assertGC`

src/main/java/hudson/cli/CLICommandInvoker.java, src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java, src/main/java/org/jvnet/hudson/test/ExtractResourceWithChangesSCM.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Fixes the following SpotBugs violations:
```
[ERROR] High: Found reliance on default encoding in hudson.cli.CLICommandInvoker.invoke(): new java.io.PrintStream(OutputStream) [hudson.cli.CLICommandInvoker] At CLICommandInvoker.java:[line 142] DM_DEFAULT_ENCODING
[ERROR] High: Found reliance on default encoding in hudson.cli.CLICommandInvoker$Result.stderr(): java.io.ByteArrayOutputStream.toString() [hudson.cli.CLICommandInvoker$Result] At CLICommandInvoker.java:[line 264] DM_DEFAULT_ENCODING
[ERROR] High: Found reliance on default encoding in hudson.cli.CLICommandInvoker$Result.stdout(): java.io.ByteArrayOutputStream.toString() [hudson.cli.CLICommandInvoker$Result] At CLICommandInvoker.java:[line 255] DM_DEFAULT_ENCODING
[ERROR] High: Found reliance on default encoding in …
```
=> Fix `DM_DEFAULT_ENCODING` SpotBugs violations

Jenkinsfile
Update the build/test matrix to include recent versions of Java, as is being done in other core components.
=> Add Java 11 to build/test matrix

src/main/java/org/jvnet/hudson/test/TestExtension.java
Extracted from #402. Without this, generating Javadoc on Java 17 fails with some obscure message about heading levels being wrong.
=> Forward compatibility with Java 17 Javadoc generation

pom.xml
The original provenance of this code was jenkinsci/jenkins@e56c9d7802, where it was added for core's `DirectoryBrowserSupportTest`. This code was retained as the test harness was split into a new repository, but it is not needed for any of the tests in this repository. Let us dispense with it and run the Windows tests in a more realistic configuration.
=> Remove `-Dfile.encoding=UTF-8` from Surefire JVM arguments

src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
Extracted from #402. Skip `MemoryAssertTest#heapUsage` on Java 17+ pending the resolution of [JENKINS-68019](https://issues.jenkins.io/browse/JENKINS-68019).
=> Skip `MemoryAssertTest#heapUsage` on Java 17+ pending JENKINS-68019

pom.xml
[SUREFIRE-1588](https://issues.apache.org/jira/browse/SUREFIRE-1588) has not seen any activity since 2018, so I think this workaround is no longer necessary.
=> Remove obsolete workaround for SUREFIRE-1588

pom.xml, src/spotbugs/excludesFilter.xml
Enumerates all known SpotBugs violations in an exclude file. This keeps our builds clean and prevents new violations from being introduced.
=> Clean up SpotBugs exclusions

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Extracted from #402. Without this, running `mvn clean verify -Dtest=org.jvnet.hudson.test.RealJenkinsRuleTest` on Java 17 hangs with
```
[INFO] Running org.jvnet.hudson.test.RealJenkinsRuleTest
=== Starting agentBuild(org.jvnet.hudson.test.RealJenkinsRuleTest)
Will load plugins: RealJenkinsRuleInit.jpi structs.jpi
Launching: [/usr/lib/jvm/java-17-openjdk-amd64/bin/java, -ea, -Dhudson.Main.development=true, -DRealJenkinsRule.location=file:jenkinsci/jenkins-test-harness/target/classes/, -DRealJenkinsRule.url=http://localhost:54116/jenkins/, -DRealJenkinsRule.description=agentBuild(org.jvnet.hudson.test.RealJenkinsRuleTest), -DRealJenkinsRule.token=b00b037d-9edc-4a9f-b55b-9898a826a625, -jar, jenkins-war-2.339-rc32171.7ef4d9496734.war, --httpPort=54116, --httpListenAddress=127.0.0.1, …
```
=> Java 17 support for `RealJenkinsRule`

Jenkinsfile, pom.xml
Update the build/test matrix to include recent versions of Java, as is being done in other core components. Note that the first version of Jenkins core that fully support Java 17 without custom `--add-opens` directives (which is needed for tests like `RealJenkinsRuleTest`) is 2.339, so we run the Java 17 tests with a newer Jenkins core version than the Java 8 and 11 tests.
=> Add Java 17 to build/test matrix

src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Additional test coverage verifying that you can run multiple Jenkins sessions with a stable URL. Useful for testing changes like #348.
=> Added `RealJenkinsRuleTest.restart`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Fixes #414
Instead of using the war on the path defined as part of the pom, or the one at war/target/jenkins.war, or using the system property affecting all tests, I can now create a RealJenkinsRule using a war (ie. a war built as part of the workflow). 
```java
@Rule
public RealJenkinsRule sc = new RealJenkinsRule()
.javaOptions("-Xmx512M")
.withHost("sc.127.0.0.1.nip.io")
.withWar(new File("/path/to/my/own/jenkins.war"));
```
=> Allow `RealJenkinsRule` to use a specific WAR file

src/main/java/org/jvnet/hudson/test/MemoryAssert.java, src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
The following tests (when run against tip-of-trunk core, Maven HPI plugin, and test harness) fail when run with Java 11, but not when run with Java 8 or Java 17:
```
mvn clean verify -Dtest=org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovyMemoryLeakTest
mvn clean verify -Dtest=org.jenkinsci.plugins.workflow.libs.LibraryMemoryTest
mvn clean verify -Dtest=org.jenkinsci.plugins.workflow.cps.CpsFlowExecutionMemoryTest
mvn clean verify -Dtest=org.jenkinsci.plugins.workflow.job.MemoryCleanupTest
```
I examined the test output from the Java 17 run and saw that it looked identical to the Java 8 run, so I think the Java 17 run really is doing the proper testing and not just passing accidentally. The Java 17 run is using the latest version of INSANE with the INSANE hooks.
I am not sure why …
=> [JENKINS-67974] `assertGC` works on Java 8 and 17 but not 11

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
I recently ran into a `RealJenkinsRule` test that called code that used `Stapler.getCurrentRequest`, which ended up failing with a confusing error message because `Stapler.getCurrentRequest` returned the request for `RealJenkinsRule.doStep` instead of `null` as would typically be the case in a test. This PR does two things to improve this case:
1. It includes the response body of `RealJenkinsRule.doStep` in the error thrown by `RealJenkinsRule.runRemotely` if `doStep` returns a non-200 response to make it easier to diagnose errors.
2. It runs the steps passed to `RealJenkinsRule.runRemotely` on a separate thread so that they cannot accidentally interact with the HTTP request for `RealJenkinsRule.doStep` if they use `Stapler.getCurrentRequest`.
=> Run RealJenkinsRule steps on a separate thread to avoid unintended interaction with the request for doStep

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Sample output below. This information can be essential when reasoning about memory usage by multiple JVMs within a single VM or container.
Java 8:
```
$ "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java"  -Djava.awt.headless=true -Xmx512m -XX:+PrintCommandLineFlags -jar "/home/basil/src/jenkinsci/text-finder-plugin/target/jenkins-for-test/WEB-INF/lib/remoting-4.5.jar"
-XX:InitialHeapSize=523530944 -XX:MaxHeapSize=536870912 -XX:+PrintCommandLineFlags -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseParallelGC 
<===[JENKINS REMOTING CAPACITY]===>channel started
Remoting version: 4.5
This is a Unix agent
Evacuated stdout
```
Java 11:
```
$ "/usr/lib/jvm/java-11-openjdk-amd64/bin/java"  -Djava.awt.headless=true -Xmx512m -XX:+PrintCommandLineFlags -jar …
```
=> Print flags specified on command line or set by ergonomics

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
In Jenkins plugin [azure-container-plugin](https://github.com/jenkinsci/azure-container-agents-plugin/blob/1bf31f31ad77524b0699e4c6266cb709eef20855/src/test/java/com/microsoft/jenkins/containeragents/AciCloudConfigTest.java#L26), there is a use case to test the correctness of the cloud configuration. The JenkinsRule has no configRoundtrip method for the cloud configuration.
=> New `configRoundtrip` method for `Cloud` configuration

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
[JENKINS-26398](https://issues.jenkins.io/browse/JENKINS-26398)
Inspired by changes being made in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180. Cleans up some tech debt from https://github.com/jenkinsci/pipeline-plugin/pull/34 & https://github.com/jenkinsci/credentials-binding-plugin/pull/3.
* Fixes `createSlave` overloads to use a more stable agent workdir compatible with `JenkinsSessionRule`.
* Introduces `InboundAgentRule` which is better suited to simulating agent disconnections.
=> [JENKINS-26398] More flexible versions of `createSlave`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Otherwise it is impossible to run tests against snapshot versions of Remoting:
```
Running: […/bin/java, -Xmx512m, -XX:+PrintCommandLineFlags, -Djava.awt.headless=true, -jar, …/remoting/target/classes, -jnlpUrl, http://localhost:…/jenkins/computer/…/slave-agent.jnlp]
Error: Invalid or corrupt jarfile …/remoting/target/classes
```
=> `InboundAgentRule` should use `Slave.JnlpJar` not `Which.jarFile(Launcher)`

src/main/java/org/jvnet/hudson/test/PropertiesTestSuite.java
see https://github.com/jenkinsci/jenkins/pull/6550#issuecomment-1121055141 https://github.com/jenkinsci/stapler/pull/357
You can't actually use a file that is valid utf-8 and not valid ISO-8859-1 in at least core right now due to https://github.com/jenkinsci/jenkins/blob/ff39fbb3cdf58d7dda17c37b8d0606dc8e9282f4/core/pom.xml#L604
But we can adjust that later when we switch to Java 11
Validated with core:
```
[ERROR] Tests run: 7139, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.743 s <<< FAILURE! - in jenkins.CorePropertiesTest
[ERROR] hudson/Messages_es.properties(org.jvnet.hudson.test.PropertiesTestSuite$PropertiesTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: jar:file:/Users/timja/.m2/repository/org/jenkins-ci/main/jenkins-core/2.347-SNAPSHOT/jenkins-core-2.34 …
```
=> Use `PropertyResourceBundle` in test suite and validate `.properties` files are not both valid UTF-8 and valid ISO-8859-1

src/main/java/org/jvnet/hudson/test/PropertiesTestSuite.java
Amends #433. Allows the use of UTF-8 property files when running on Java 11 (i.e., when running on Jenkins 2.357 or greater). Note that this relies on `Jenkins#getVersion` having been initialized, which is only the case in plugin tests because the Jelly tests (which actually start Jenkins) have previously executed in the same VM and is only the case in core tests after some adjustments in https://github.com/jenkinsci/jenkins/pull/6719. Tested in a plugin (after converting a `.properties` file from ASCII to UTF-8) and in core (in the context of https://github.com/jenkinsci/jenkins/pull/6719). It is recommended to review this diff with the "Hide whitespace" feature enabled.
=> [JENKINS-41729] Allow UTF-8 property files

src/main/java/org/jvnet/hudson/test/LoggerRule.java, src/test/java/org/jvnet/hudson/test/LoggerRuleTest.java
Previously the matcher showed the LoggerRule toString:
```
Expected: has LogRecord with level \"INFO\" with a message matching \"Entry 2\" 
but: was <org.jvnet.hudson.test.LoggerRule@60dcc9fe>
```
=> Show log records when `RecordedMatcher` doesn't match

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/org/jvnet/hudson/main/UseRecipesWithJenkinsRuleTest.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java, src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java
While debugging some test failures recently, I found some of the error messages less than helpful. Using Hamcrest matchers consistently results in better error messages and a smoother debugging experience.
=> Use Hamcrest matchers where possible

RealJenkinsRuleInit/pom.xml, pom.xml
Consistent with the baseline in `plugin-pom` and `maven-hpi-plugin`. I hope this should not be controversial as this is still a pretty ancient version of Jenkins.
=> Bump baseline from 2.204 to 2.249

src/main/java/org/jvnet/hudson/test/NoListenerConfiguration.java
Required for jenkinsci/jenkins#6805, #453, jenkinsci/jenkins#6802.
When the application is started from `java -jar jenkins.war`, `hudson.WebAppMain` runs to initialize the application. In the context of the test harness, we do not want this to happen, since the test harness initializes Jenkins itself.
The current method does this with a call to `context.setEventListeners(null)` in `NoListenerConfiguration`. This has three problems:
1. It is `final`, forcing the need for copypasta in https://github.com/jenkinsci/jenkins/blob/6de288f424f3a76d9fab9e54e379ca171b08e158/test/src/test/java/hudson/util/BootFailureTest.java#L79-L80=.
2. It does not work in Jetty 10, causing opaque test failures in `JenkinsRuleTest`.
3. It not only clears the listener for `hudson.WebAppMain`, which is its purpose, …
=> Forward compatibility with Jetty 10 in `JenkinsRule`

src/main/java/org/jvnet/hudson/test/WarExploder.java
See [JENKINS-69044](https://issues.jenkins.io/browse/JENKINS-69044). `WarExploder` contains two code paths that do the same thing: a standard code path for Maven, and a fallback code path for IntelliJ. The standard code path for Maven hunts down the WAR file by looking for `winstone.jar` and a class in the `executable` package. Prior to https://github.com/jenkinsci/jenkins/pull/6706 this was working as intended with `winstone.jar` in the root of the WAR file and the class in the `executable` package being the placeholder `executable.Executable`, but https://github.com/jenkinsci/jenkins/pull/6706 moved `winstone.jar` into the `executable` package and got rid of the placeholder class `executable.Executable` in favor of the real `Main` class (previously in the unnamed package but moved to …
=> [JENKINS-69044] Adapt to executable WAR changes in `JenkinsRule`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Cloudbees CI reported a number of flaky tests encountering in [operations-center-context plugin](https://github.com/cloudbees/operations-center-context/blob/master/src/test/java/com/cloudbees/opscenter/artifacts/RemoteArtifactCopyBuilderTest.java#L98)
Logs:
[RemoteArtifactCopyBuilderTest.txt](https://github.com/jenkinsci/jenkins-test-harness/files/9189993/RemoteArtifactCopyBuilderTest.txt)
[RemoteArtifactCopyBuilderTest_stacktrace.txt](https://github.com/jenkinsci/jenkins-test-harness/files/9189995/RemoteArtifactCopyBuilderTest_stacktrace.txt)
Changes made in scope of this PR:
1. Handle empty port. [514bfbf](https://github.com/jenkinsci/jenkins-test-harness/pull/465/commits/514bfbf4b6cc5d93e74d341de0c16f5146b78fe7)
2. Stop proc once. …
=> Handle empty port to fix RealJenkinsRule flakiness

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Amends #348, as it broke semantic of `#getUrl` which now must be called
after starting Jenkins.
=> Clarify new semantic of #getUrl

.github/dependabot.yml
@oleg-nenashev is no longer active in this repository.
=> Remove `oleg-nenashev` from `dependabot.yml`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
This change also introduces a new structure to capture the input and output payload of the doStep call which avoids depending on indexed list.
In case an exception is raised during the step call, the original stacktrace is accessible as follow
```
org.jvnet.hudson.test.RealJenkinsRule$StepException: Remote step threw an exception
at org.jvnet.hudson.test.RealJenkinsRule.runRemotely(RealJenkinsRule.java:666)
at org.jvnet.hudson.test.RealJenkinsRule.then(RealJenkinsRule.java:441)
at org.jvnet.hudson.test.RealJenkinsRuleTest.testThrowsException(RealJenkinsRuleTest.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
=> RealJenkinsRule: get the full stacktrace when a remote call fails

src/main/java/hudson/slaves/NodeProvisionerRule.java
As of https://github.com/jenkinsci/jenkins/pull/7210 `NodeProvisionerRule` will no longer be used anywhere in the Jenkins ecosystem, so deprecate it in favor of `RealJenkinsRule`. I suspect it was never realistic anyway.
=> Deprecate `NodeProvisionerRule`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Various improvements to `InboundAgentRule`:
- Support WebSocket
- Support secrets
- Support skipping agent start
- Improve determinism by waiting for `SlaveComputer#_connect` to finish after adding the agent but before starting it
- Add work directory options
- Use thread-safe data structures
The motivation behind this is to enable most tests in Jenkins core to be converted to this rule. That way flakiness fixes can be implemented in one place and apply to all tests, which isn't possible with the copypasta we have today.
Once I get an incremental I'll post a core PR demonstrating how this is used.
=> Improve `InboundAgentRule`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Contrary to the claim in https://github.com/jenkinsci/jenkins-test-harness/pull/465#discussion_r935640464, chained & suppressed exceptions seem to be displayed fine in test output for me, so logging them again just creates noise. Possibly @Pldi23 was using some Maven project that neglected to disable stack trace trimming as Jenkins parent POMs do and which later became the default because that system is so broken.
=> Removing redundant stack trace from output

pom.xml
`maven-enforcer-plugin` `requireUpperBoundsCheck` rule will retrieve transitive dependencies of all plugins specified in the pom, which use various versions of jenkins core. These depend on old versions of stapler-adjunct-xxx, which used to depend on stapler using a version range. This causes indirectly to retrieve all versions of stapler, causing unnecessary additional time to download.
Adding `jenkins-core` to `dependencyManagement` directly allows to cut this since no older jenkins version will be resolved, and thus no old stapler artifacts.
=> Add jenkins-core to dependencyManagement to avoid pulling all stapler versions

pom.xml
Fixes
```
[2022-10-13T07:50:05.173Z] [WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-enforcer-plugin @ org.jenkins-ci.main:jenkins-test-harness:${changelist}, /home/jenkins/workspace/Core_jenkins-test-harness_PR-499/pom.xml, line 290, column 15
```
Stapler actually pulls guava 11.0.1 so there doesn't seem to be an upperboundcheck problem.
https://github.com/jenkinsci/stapler/pull/123
=> Exclusion is no longer needed

src/main/java/org/jvnet/hudson/test/SimpleCommandLauncher.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Noticed when testing on Java 17 without custom `--add-opens` directives: `SimpleCommandLauncher` attempts to serialize an `EnvVars` variable, which is a sorted map, which XStream cannot serialize because of:
```
java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Slave#launcher for class hudson.slaves.DumbSlave
at hudson.XmlFile.write(XmlFile.java:220)
at jenkins.model.Nodes.persistNode(Nodes.java:183)
at jenkins.model.Nodes.addNode(Nodes.java:148)
at jenkins.model.Jenkins.addNode(Jenkins.java:2206)
at org.jvnet.hudson.test.JenkinsRule.createSlave(JenkinsRule.java:1061)
at com.cloudbees.jenkins.support.configfiles.AgentsConfigFileTest.agentsConfigFile(AgentsConfigFileTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native …
```
=> Java 17 support for `SimpleCommandLauncher`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Add several methods to :
* use this rule in the context of `RealJenkinsRule`
* use this rule in the context of CloudBees way of starting up agents.
See downstream usage in https://github.com/jenkinsci/jenkins/pull/7381
=> Support of `RealJenkinsRule` in `InboundAgentRule`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
For example you may wish to test behavior of Jenkins behind a reverse proxy and define a particular root URL explicitly.
=> `RealJenkinsRule` should not overwrite `JenkinsLocationConfiguration` if otherwise set

src/main/java/org/jvnet/hudson/test/PluginAutomaticTestBuilder.java
Sometimes when testing a number of plugins at once, `InjectedTest.testPluginActive` would fail saying something like `Plugin workflow-support failed to start` where the problem is in `some-other-plugin/pom.xml` which has a (perhaps `test`-scoped) dependency on `workflow-support`, for example because a BOM-related mistake led to `some-other` plugin using an older transitive dep (`workflow-api`, say). The problem is that nothing in the failure stack trace mentions `some-other` plugin. In something like `bom/Jenkinsfile` this is not terrible because each tested plugin is (currently!) run in its own `parallel` branch, causing the `junit` step to record the tested plugin name indirectly in the test report, but that is pretty fragile and does not work at all when running a bunch of plugins …
=> Some `InjectedTest.testPluginActive` failures neglected to identify tested plugin

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Sometimes when defining complex suites of tests using `RealJenkinsRule` it is helpful to be able to define reusable `Step` implementations (classes or method handles) and run a series of them at once. This makes that process slightly more convenient and faster.
=> Accept multiple `Step`s in `then` and `runRemotely`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java, src/main/java/org/jvnet/hudson/test/PrefixedOutputStream.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/PrefixedOutputStreamTest.java
At CloudBees we often multiple `RealJenkinsRule` rules simultaneously to model the interaction among multiple controllers. It is much easier to follow log output when log lines are prefixed with a controller identifier, and (when running interactively) are colored.
=> Allow `RealJenkinsRule` instances to specify a `name` & `color`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Does not make much of a difference in practice one way or another, but in principle the versions of `#stop` that take `JenkinsRule`/`RealJenkinsRule` should be preferred whenever possible (i.e., when not being invoked by JUnit during teardown), since those versions make tests more deterministic by waiting for the agent to disconnect from the controller. To test this I ran `mvn clean verify -Dtest=hudson.slaves.JNLPLauncherRealTest` with these changes.
=> Plumb through `JenkinsRule`/`RealJenkinsRule` when possible

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
=> Document #359

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
This Maven property can be helpful to avoid conflicts between parallelized tests when using test services, if you cannot reliably randomize ports. Needs https://github.com/jenkinsci/plugin-pom/pull/645 to ensure the property gets propagated from Maven to the Surefire booter JVM.
=> Allow `RealJenkinsRule` controllers to know `surefire.forkNumber`

Jenkinsfile, pom.xml
The first of several PRs to require Java 11 or newer. More cleanup is planned after this PR now that the baseline has been increased to 2.361.
=> Require Java 11 or newer

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/PropertiesTestSuite.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/main/java/org/jvnet/hudson/test/WarExploder.java
Removes logic for old Jenkins versions that is no longer needed because the baseline is now 2.361. I tested this in core with `mvn clean verify -Dtest=hudson.bugs.JnlpAccessWithSecuredHudsonTest,hudson.diagnosis.HudsonHomeDiskUsageMonitorTest,hudson.model.ItemsTest,hudson.model.JobTest,hudson.model.PasswordParameterDefinitionTest,hudson.model.QueueRestartTest,hudson.model.QueueTest,hudson.security.LoginTest,hudson.slaves.JNLPLauncherRealTest,hudson.slaves.NodeProvisionerTest,hudson.util.RobustReflectionConverterTest,jenkins.CoreAutomaticTestBuilder,jenkins.model.JenkinsLogRecordsTest,jenkins.model.JenkinsTest,jenkins.security.ApiCrumbExclusionTest,jenkins.security.ApiTokenPropertyTest,jenkins.security.BasicHeaderProcessorTest,jenkins.util.SetContextClassLoaderTest,jenkins.util.SystemProper …
=> Remove logic for old Jenkins versions

src/main/java/com/gargoylesoftware/htmlunit/html/HtmlElementUtil.java, src/main/java/hudson/cli/CLICommandInvoker.java, src/main/java/org/jvnet/hudson/test/ExtractChangeLogParser.java, src/main/java/org/jvnet/hudson/test/ExtractChangeLogSet.java, src/main/java/org/jvnet/hudson/test/ExtractResourceWithChangesSCM.java, src/main/java/org/jvnet/hudson/test/FakeChangeLogSCM.java, src/main/java/org/jvnet/hudson/test/HudsonHomeLoader.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/InboundAgentRule.java, src/main/java/org/jvnet/hudson/test/JellyTestSuiteBuilder.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/LoggerRule.java, src/main/java/org/jvnet/hudson/test/MemoryAssert.java, src/main/java/org/jvnet/hudson/test/MockAuthorizationStrategy.java, src/main/java/org/jvnet/hudson/test/MockFolder.java, src/main/java/org/jvnet/hudson/test/PrefixedOutputStream.java, src/main/java/org/jvnet/hudson/test/PretendSlave.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/main/java/org/jvnet/hudson/test/ResponseCapturingOutput.java, src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java, src/main/java/org/jvnet/hudson/test/SingleFileSCM.java, src/main/java/org/jvnet/hudson/test/TestBuilder.java, src/main/java/org/jvnet/hudson/test/TestNotifier.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java, src/test/java/org/jvnet/hudson/test/MemoryAssertTest.java, src/test/java/org/jvnet/hudson/test/PrefixedOutputStreamTest.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Tested in core with `mvn clean verify -Dtest=hudson.bugs.JnlpAccessWithSecuredHudsonTest,hudson.cli.AddJobToViewCommandTest,hudson.cli.BuildCommandTest,hudson.cli.CancelQuietDownCommandTest,hudson.cli.ClearQueueCommandTest,hudson.cli.ComputerStateTest,hudson.cli.ConnectNodeCommandTest,hudson.cli.ConsoleCommandTest,hudson.cli.CopyJobCommandTest,hudson.cli.CreateJobCommandTest,hudson.cli.CreateNodeCommandTest,hudson.cli.CreateViewCommandTest,hudson.cli.DeleteBuildsCommandTest,hudson.cli.DeleteJobCommandTest,hudson.cli.DeleteNodeCommandTest,hudson.cli.DeleteViewCommandTest,hudson.cli.DisablePluginCommandTest,hudson.cli.DisconnectNodeCommandTest,hudson.cli.EnableJobCommandTest,hudson.cli.EnablePluginCommandTest,hudson.cli.GetJobCommandTest,hudson.cli.GetNodeCommandTest,hudson.cli.GetViewComman …
=> Use Java 11 language features where possible

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Kubernetes-plugin is running its tests within a kubernetes pod running in Kind.
During test execution, agents need to loopback to the running controller running in another container, and so the controller needs to bind another network interface than localhost.
A [special](https://github.com/jenkinsci/kubernetes-plugin/blob/54f40a5e7fb1798bad69977b00fa8634260d8852/src/test/java/org/jvnet/hudson/test/JenkinsRuleNonLocalhost.java) version of JenkinsRule is used for regular tests, considering prior attempts to introduce such option were not merged.
For RealJenkinsRule-based tests, it seems much simpler to have the option available directly in the framework.
See usage in https://github.com/jenkinsci/kubernetes-plugin/pull/1290
Relates to …
=> `RealJenkinsRule`: option to provide a custom port/listen address

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
When writing RJR tests involving multiple controller instances, it's tedious to debug because each controller starts with a random debug port, and it changes on each run.
When debugging interactively, it's easier to rely on static ports (which can be specified in a test base class declaring the different controller instances involved in tests). I've found as well `server=n` to be useful for this case as test cases can involve restarts, and IDE can set up their debugger in server mode (so that the VM connects to it) with auto restart.
=> Let callers specify some debug options

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
As of https://github.com/jenkinsci/winstone/pull/310 we will get final log messages even without an explicit call path to `Jenkins.cleanUp`, so there is no need for a special `exit` endpoint.
=> Use `ProcessHandle.destroy` to implement `RealJenkinsRule.stopJenkins`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Amending #488. It is conventional for wrapper exceptions to include `cause.message` in their own `message` as a suffix. (Also this is [treated specially by `Functions.printThrowable`](https://github.com/jenkinsci/jenkins/blob/4300daa6679476b1de606ed4636a0542e98231d1/core/src/main/java/hudson/Functions.java#L1696-L1698) though it is unlikely that would be applied to a JUnit error.)
=> Include details about `cause` in `StepException.message`

src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java
Now that Commons Lang 3 is a library plugin, the test harness shouldn't be using it, since a plugin could potentially declare a dependency on a different version that might conflict with the version provided by the test harness. Unfortunately, though, the test harness exposes a `ImmutablePair` type in its public API (via `JenkinsRule._createWebServer`), making it tough to implement this. But we should at least not make the problem worse by using Commons Lang 3 in a private field as we do in `JmhBenchmarkState`. Here we switch to a Java Platform type to lessen our dependency on this problematic library. This should be covered by `BenchmarkTest`.
=> Reduce usage of Commons Lang 3

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
waiting for the agent could be an infinite loop if the agent had not connected when we enter the retry (ie computer was null).
Also spotbugs was complaining about a redundant null check from `URLConnection.getInputStream()` as that will return a stream or throw an `UnknownServiceException` if input is not supported - but never null.
=> Fix potential infinite loop in `InboundAgentRule`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Based on CI build failures in https://github.com/jenkinsci/workflow-cps-plugin/pull/669 (see for example [this test output](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/PR-669/5/testReport/org.jenkinsci.plugins.workflow.cps/CpsFlowDefinitionRJRTest/windows_11___Build__windows_11____flushLogsOnShutdown/)), I am suspicious that beyond the lack of shutdown-related log messages on older versions of Jenkins, https://github.com/jenkinsci/jenkins-test-harness/pull/544 might not shut down Jenkins cleanly on Windows, in particular I think `Jenkins.cleanUp` might not run and terminators may be skipped.
This PR injects an `ItemListener` dynamically into Jenkins using `ExtensionList.add` that writes a file in `onBeforeShutdown`, which is called by `Jenkins.cleanUp`, and after the …
=> Revert #544 so that `RealJenkinsRule` shuts down cleanly on Windows

docs/CHANGELOG-OLD.md, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java
Fixes #518 by adapting to https://github.com/jenkinsci/jenkins/pull/2996 by replacing links to `jenkins-ci.org` with links to `jenkins.io` and using HTTPS rather than HTTP to access the Update Center. To test this I exercised the code path from a plugin build and verified in a debugger that the new URL was being used and that it was cached as expected. I also successfully ran `mvn clean verify -Dtest=hudson.cli.InstallPluginCommandTest,hudson.core.PluginManagerOverrideTest,hudson.CustomPluginManagerTest,hudson.model.DownloadService2Test,hudson.model.DownloadServiceTest,hudson.model.UpdateCenter2Test,hudson.model.UpdateCenterConnectionStatusTest,hudson.model.UpdateCenterCustomTest,hudson.model.UpdateCenterPluginInstallTest,hudson.model.UpdateCenterTest,hudson.model.UpdateSiteTest,hudson.Plu …
=> HTTPS for Update Center

src/main/java/org/jvnet/hudson/test/WarExploder.java
Minor fixups to #561; should improve the error message in some pathological cases. I repeated the testing from #561 and also tested that the error message was correct when heading down this bizarre code path without a primed `~/.m2` directory.
=> Fixups to #561

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
thanks to @basil for finding this out in https://github.com/jenkinsci/jenkins/pull/7727#discussion_r1155349075
Required for https://issues.jenkins.io/browse/JENKINS-70906
I've tested this by enabling the option in the failing test in the above pull request and it makes the test pass
=> Enable fetch polyfill with web client

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
`tunnel` and `label` options, as well as a `webSocket` overload taking `boolean` to make it easier to parameterize tests.
=> More options for `InboundAgentRule` launching

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Can matter for tests which define a specific root URL for a controller.
=> Honor `Jenkins.rootUrl` when launching `InboundAgentRule`

pom.xml
Both modules named are deprecated since 2019, in favor of `hamcrest` where the logic of both modules live on since then.
Consumers are advised to replace hamcrest-x with hamcrest, if not already done.
=> Remove deprecated `hamcrest-core` and `hamcrest-library` modules

src/main/java/org/jvnet/hudson/test/JenkinsMatchers.java, src/main/java/org/jvnet/hudson/test/LoggerRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java, src/test/java/org/jvnet/hudson/test/RestartableJenkinsRuleTest.java
With https://github.com/jenkinsci/jenkins-test-harness/pull/587 in mind, we can make use of the methods from the `hamcrest` package, which is the drop-in replacement for the deprecated -core package.
The code from the deprecated package has been merged in, and the methods return the same, nonetheless I applied the `breaking` label because the method signature changes.
Testing with core in https://github.com/jenkinsci/jenkins/pull/8046 revealed no issues.
=> Replace hamcrest matchers with methods from non-deprecated packages

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Fixes #366
This detects if the jacoco agent is part of the test jvm command line, and copies it to forked jvms.
Jacoco supports appending to the coverage file data, each jvm will report using a different session id.
Can be tested in a Jenkins plugin using RealJenkinsRule and passing `mvn verify -Penable-jacoco` to verify that covered classes include expected classes.
=> Support of jacoco agent in forked Jenkins instances

src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
When the git plugin and the gitlab plugin upgraded to parent pom 4.64, their tests failed on Windows. The Java delete() method on Windows throws an access denied exception when asked to delete a read-only file.  Command line git creates read-only files in the objects directory when it clones a repository.
This test creates a read-only file and relies on the JenkinsRule cleanup process to remove the file.
[Draft pull request](https://github.com/jenkinsci/git-plugin/pull/1454) submitted to the git plugin confirming that clearing the "read-only" permission on Windows files allowed the 100+ failing tests to pass with parent pom 4.64.
Automated test written that confirms read-only files are deleted as expected on Unix and that read-only files are not deleted on Windows.
The [first …
=> Dispose of Windows read-only temporary files

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
The fewer third-party dependencies this test framework has, the easier it is to maintain.
=> Reduce usages of Guava

src/main/java/org/jvnet/hudson/test/WarExploder.java
Hi!
This PR fixes an issue where the `WarExploder` is unable to find a copy of `jenkins-war` in the Gradle cache on disk if the checksum for the specified version begins with a zero. For some reason the fine folks working on Gradle decided to drop leading zeros from checksums. According to https://discuss.gradle.org/t/sha-1-checksum-portion-of-file-path-in-gradle-cache-is-missing-leading-zeros/1244/2 it could be to save characters in order to respect file path limitations. Either way, because the Gradle cache is an internal API, there's no guarantees in the way the test harness is trying to use it.
I compiled my changes and included them into a Jenkins JobDSL repo we have where I noticed the issue earlier today. With version `1954.v2e3fd5465b_a_6` I saw the following error when attempting …
=> `WarExploder` does not find the Jenkins WAR in the Gradle cache if its SHA-1 hash begins with a 0

pom.xml, src/main/java/com/gargoylesoftware/htmlunit/WebClientUtil.java, src/main/java/com/gargoylesoftware/htmlunit/WebResponseListener.java, src/main/java/com/gargoylesoftware/htmlunit/html/DomNodeUtil.java, src/main/java/com/gargoylesoftware/htmlunit/html/HtmlElementUtil.java, src/main/java/com/gargoylesoftware/htmlunit/html/HtmlFormUtil.java, src/main/java/hudson/security/pages/SignupPage.java, src/main/java/org/jvnet/hudson/test/HudsonPageCreator.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/rhino/CallStackFrame.java, src/main/java/org/jvnet/hudson/test/rhino/JavaScriptDebugger.java, src/test/java/org/jvnet/hudson/main/UseRecipesWithJenkinsRuleTest.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
Part of https://github.com/jenkinsci/jenkins-test-harness/issues/568
Ran tests in the project
=> Upgrade to htmlunit 3.x

src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/PropertiesTestSuite.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/main/java/org/jvnet/hudson/test/SingleFileSCM.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Now that we require Java 11 or newer, we do not need to use this Apache Commons I/O library. The fewer third-party libraries we consume, the easier it is to maintain this component.
Ran the `jenkins-test-harness` tests, the `text-finder-plugin` tests, and these core tests: `mvn clean verify -Dtest=hudson.model.DirectoryBrowserSupportTest,hudson.console.ConsoleAnnotatorTest,jenkins.util.SystemPropertiesTest,jenkins.CoreAutomaticTestBuilder`.
=> Remove usages of `org.apache.commons.io.IOUtils`

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
This has been dead code since we migrated away from `org.mortbay.jetty` in commit eec94edfe6a4708ebb3ea068d94d7a8e6f37996e in 2016.
=> Stop suppressing Jetty logs which no longer exist

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
`com.gargoylesoftware.htmlunit.javascript.host.Document` was renamed to `com.gargoylesoftware.htmlunit.javascript.host.dom.Document` in HtmlUnit 2.16 in 2015, and `StrictErrorHandler` was removed in HtmlUnit 2.35.0 in 2019, meaning these lines have been dead code for the better part of the past 8 years. Also, the original reason they were added was to work around problems with Prototype which we are now removing, so there is no motivation to rewrite this functionality to work with modern versions of HtmlUnit.
=> Revert jenkinsci/jenkins@84d49ceef2

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
The comment had become out of date with regard to the method's primary purpose. Also the `super(BrowserVersion.BEST_SUPPORTED)` call was redundant, as the default no-argument constructor was already using `BrowserVersion.BEST_SUPPORTED`.
=> Improve Javadoc for `createWebClient`

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Recent versions of Jetty, which we have been using since 2016 or so, use `org.eclipse.jetty.server.Request.maxFormContentSize` rather than `org.mortbay.jetty.Request.maxFormContentSize` to set the maximum form content size. While I was here I also updated this to use a constant rather than a hard-coded string to make this code easier to maintain going forward. I tested this in Jenkins core and BOM and it did not make anything worse. While I am not fully convinced this setting is still needed, I am also not fully convinced that this setting is not needed either. Making the code work as intended (rather than as it was working previously) seems to be at least a mildly positive step in the right direction in the sense of improving readability. If someone can clearly demonstrate with certainty …
=> Use correct key for `Request.maxFormContentSize`

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java
This PR does not attempt to solve JENKINS-14749 (which I think was solved but regressed at some point), but it does synchronize the code in `HudsonTestCase` with that in `JenkinsRule` by favoring the version in `JenkinsRule` and applying that to `HudsonTestCase`. Once synchronized in this PR, the two versions should be kept in sync going forward.
Will rely on the CI build.
```[tasklist]
```
=> Synchronize `CSSErrorHandler#ignore` in `HudsonTestCase` with the primary version in `JenkinsRule`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
It was printing a stacktrace with Connection refused (Connection refused)
This now prints the exit code.
```[tasklist]
```
=> Improve the case where the Jenkins process stopped unexpectedly

src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
As a prerequisite to #550, remove usages of Commons Lang 3 from this repository. Although Commons Lang 3 was part of a public API, in practice no consumers existed other than a class in a different package in this repository itself (thankfully). In any case, the use of a tuple in the return type was unnecessary — the `Server` object has a reference to the `ServletContext` which can be fished out by any consumers that need it.
Ran Text Finder plugin tests with this PR.
```[tasklist]
```
=> Remove usages of Commons Lang 3

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
`JenkinsRule.showAgentLogs` is fine for a single Jenkins session, but since the log text is streamed back to the controller, it is not well suited for cross-session tests (like https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/323).
=> `InboundAgentRule.Options.Builder.withLogger`

pom.xml, src/main/java/org/jvnet/hudson/test/WarExploder.java
exploding the war for test had a race condition that caused tests to randomly fail if they had multiple tests running in parallel using JenkinsRule.
this switches a poor mans locking with race conditions to use the OS level file locking facilities
in this project created 20 test classes like the following :
```
package org.jvnet.hudson.test.jr;
import org.junit.Rule;
import org.junit.Test;
import org.jvnet.hudson.test.JenkinsRule;
public class JR1Test {
@Rule
public JenkinsRule rule = new JenkinsRule();
@Test
public void anything() {
}
}
```
ran  `rm -fr target\jenkins-for-test && mvn test -DforkCount=20 -Dtest=JR*Test`  (on windows)
Observed that the tests did not fail and the logging is expected
```
[INFO] --- surefire:3.1.2:test (default-test) @ jenkins-test-harness ---
[INFO] Using …
```
=> remove flakyness expolding war for test

pom.xml
Amends #635
- The default value of `forkCount` is 1 so not necessary to define it to 1 here
- The default property for `<forkCount>` is `${forkCount}` so not necessary to define it to `${forkCount}` here
=> Remove unnecessary defaults

src/main/java/org/jvnet/hudson/test/RemainingActivityListener.java
Helpful to see cases where #198 revealed something nondeterministic about test execution.
=> Adding `RemainingActivityListener` for diagnosis

src/main/java/org/jvnet/hudson/test/MemoryAssert.java
We get flaky test failures like this regularly in `jenkinsci/bom`:
```
java.lang.NoClassDefFoundError: org/netbeans/insane/hook/MakeAccessible
at org.netbeans.insane.impl.InsaneEngine.processClass(InsaneEngine.java:224)
at org.netbeans.insane.impl.InsaneEngine.process(InsaneEngine.java:185)
at org.netbeans.insane.impl.InsaneEngine.traverse(InsaneEngine.java:73)
at org.netbeans.insane.impl.LiveEngine.traceImpl(LiveEngine.java:165)
at org.netbeans.insane.impl.LiveEngine.trace(LiveEngine.java:143)
at org.jvnet.hudson.test.MemoryAssert.fromRoots(MemoryAssert.java:297)
at org.jvnet.hudson.test.MemoryAssert.assertGC(MemoryAssert.java:208)
at org.jvnet.hudson.test.MemoryAssert.assertGC(MemoryAssert.java:148)
at org.jenkinsci.plugins.workflow.libs.LibraryMemoryTest.loaderReleased(LibraryMemoryTest …
```
=> Make failure to load NetBeans Insane hook non-fatal

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Matching change to https://github.com/jenkinsci/jenkins/pull/8513
This should help to identify race conditions during tests without causing too much noise as it only kicks in just before cleaning up the instance.
```[tasklist]
```
=> Set up file logging when shutting down the Jenkins test instance.

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
When running on a recent enough version of Remoting, avoid `-jnlpUrl` in favor of the simpler non-deprecated semantics that avoid an unnecessary round-trip to the server.
Ran `mvn clean verify -Dtest=hudson.bugs.JnlpAccessWithSecuredHudsonTest,hudson.cli.OfflineNodeCommandTest,hudson.model.ProjectTest,hudson.node_monitors.ResponseTimeMonitorTest,hudson.slaves.AgentInboundUrlTest,hudson.slaves.JNLPLauncherRealTest,hudson.slaves.NodeParallelTest,jenkins.agents.JnlpProtocol4ProxyHandlerTest,jenkins.agents.WebSocketAgentsTest,jenkins.security.Security218Test,jenkins.slaves.restarter.JnlpSlaveRestarterInstallerTest` with both code paths (old and new Remoting).
=> Avoid `-jnlpUrl` if running on a recent enough version of Remoting

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Started trying to use #671 in some proprietary functional tests and soon found a number of places with three args would be useful, and even a couple taking four args. (Example: set up an SSH agent with a name, host, port, and credentials id.)
=> `RealJenkinsRule` overloads taking 3–4 args

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
I found an exotic case (in a proprietary test) where it was necessary to pass `--webroot` and `--pluginroot` to Jenkins processes to avoid corruption of unpack directories while changing component versions.
=> `RealJenkinsRule.jenkinsOptions`

src/main/java/org/jvnet/hudson/test/junit/jupiter/JUnit5JenkinsRule.java, src/main/java/org/jvnet/hudson/test/junit/jupiter/JenkinsExtension.java, src/test/java/org/jvnet/hudson/test/junit/jupiter/JenkinsRuleClassResolverTest.java
See [JENKINS-72387](https://issues.jenkins.io/browse/JENKINS-72387).
I'd like to add support for creating one running Jenkins instance per Test Class, when using the JUnit5 extension points.
Due to how the JenkinsRule and underlying contexts expect population of the Jenkins `testDescription`, some refactoring of was required. This was necessary to find all annotations that may exist in all contexts - which would define the pre-test state of the Jenkins instance.
All previous tests pass, including the original which tested code this PR has refactored/modified (`JenkinsRuleResolverTest`).
Added an additional test  (`JenkinsRuleClassResolverTest`) to ensure the explicit feature was validated. 
```[tasklist]
```
=> [JENKINS-72387] Provide JUnit5 Class (static) context for JenkinsRule

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Can be used to launch the JuT using any JVM instead of always delegating to JAVA_HOME.
Useful due to the upcoming support process for [different JVM versions](https://www.jenkins.io/blog/2023/11/06/introducing-2-2-2-java-support-plan/) as it would allow to create RJR test configurations that share the same code but run with different JVMs, like 17 and 21
Manual tested by creating a test that uses a custom location on my local system.
There are unit tests that ensures the new code works as expected also.
```[tasklist]
```
=> Provide the means to customize the folder containing the java executable for RJR

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Fixes #365.
In addition to what is described in #365, I have a case where I would like to use `RealJenkinsRule` dynamically in tests in a way that is not well suited to `@Rule`/`@ClassRule`. This PR adds a `deprovision` method, which deletes `JENKINS_HOME`, and an `isAlive` method, which checks whether the Jenkins process is alive. In combination with the new `withLazyProvisioning` method that delays `JENKINS_HOME` initialization until Jenkins first starts, this allows `RealJenkinsRule` to be instantiated, provisioned, started, stopped, and deprovisioned fully dynamically. The `deprovision` and `isAlive` methods can be ignored in most cases.
```[tasklist]
```
=> Allow `RealJenkinsRule` to delay `JENKINS_HOME` initialization until first startup using new `prepareHomeLazily` method

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Otherwise putting this in a `finally` block can obscure the root cause of a test failure particularly if the test failed with a timeout.
=> Let `InboundAgentRule.stop` tolerate a dead controller in `RealJenkinsRule` mode

src/main/java/org/jvnet/hudson/test/MockQueueItemAuthenticator.java
https://github.com/jenkinsci/jenkins-test-harness/pull/695#issuecomment-1854613775
=> Restore compatibility after JEP-227 updates

src/main/java/org/htmlunit/html/HtmlFormUtil.java
Spent hours tracking down bizarre behavior which I could finally trace to an error in an `HtmlForm.submit` call (as well as a bogus return value from `getSubmitButton` highlighted by https://github.com/jenkinsci/jenkins/pull/8554 which I will deal with separately). You do not `return` from a `finally` block.
Dates to https://github.com/jenkinsci/jenkins/pull/1774.
=> Do not swallow exceptions in `HtmlFormUtil`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Fixes #359. Needed for https://github.com/jenkinsci/script-security-plugin/pull/553.
=> Handle `AssumptionViolatedException`

pom.xml
Reverts jenkinsci/jenkins-test-harness#715
Seems to be causing intermittent test failures in core as in https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8873/8/
=> Revert "Bump org.jenkins-ci.main:jenkins-test-harness-htmlunit from 164.v87e5a_1809c10 to 168.v36080d5e8d36"

src/main/java/org/jvnet/hudson/test/PrefixedOutputStream.java
Very similar to #728, I have found that near-simultaneous printing of prefixed output lines can wind up causing display corruption and messing up ANSI display codes. This seems to fix it, at least in limited testing.
=> Add synchronization to `PrefixedOutputStream`

src/main/java/org/jvnet/hudson/test/TailLog.java
The default check time for `Tailer` is 1s. For tests where typically only one or a few files are being tailed, so performance is unimportant, we would prefer something closer to real time so build log lines appear closer to related system log messages. Compare https://github.com/jenkinsci/jenkins-test-harness/blob/fafaf2080a058b49d95c2dbf6f63d93e99ad50d6/src/main/java/org/jvnet/hudson/test/BuildWatcher.java#L60-L67 and to a lesser extent https://github.com/jenkinsci/jenkins-test-harness/blob/fafaf2080a058b49d95c2dbf6f63d93e99ad50d6/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L1627-L1632
=> `TailLog` closer to real time

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
If a test times out while waiting for a step to complete (typically a step which waits indefinitely for some condition), you would get a weird HTTP-level error as the test failure, and have to dig into other logs to actually see what happened. New test case without fix:
```
java.lang.AssertionError: unexpected exception type thrown; expected:<org.jvnet.hudson.test.RealJenkinsRule.StepException> but was:<java.net.ConnectException>
at org.junit.Assert.assertThrows(Assert.java:1020)
at org.junit.Assert.assertThrows(Assert.java:981)
at org.jvnet.hudson.test.RealJenkinsRuleTest.timeoutDuringStep(RealJenkinsRuleTest.java:339)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at …
```
=> Clearer handling of test timeout during step

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
While running `workflow-durable-task-step` tests on a proprietary environment with only IPV6 networking enabled I found some parts of RJR that were not fully IPV6 compatible. This PR tries to fix those parts so RJR can be used in both IPV4 and IPV6 environments.
```[tasklist]
```
=> Adapt to IPV6 envs

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
see https://github.com/jenkinsci/jenkins/pull/9148#issuecomment-2049412794
I've searched the repository for other issues with this pattern but there's no others
https://github.com/timja/jenkins-test-harness/blob/d8347b0b5778efb5a5121e2df878b35f7bb94e39/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L2329-L2333
```[tasklist]
```
=> Enable fetch polyfill in search method

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Jetty 10:
```
jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
145:    public static final String MAX_FORM_CONTENT_SIZE_KEY = "org.eclipse.jetty.server.Request.maxFormContentSize";
```
Jetty 12:
```
jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/FormFields.java
42:    public static final String MAX_LENGTH_ATTRIBUTE = "org.eclipse.jetty.server.Request.maxFormContentSize";
```
As you can see, the string is the same, but now lives in `FormFields.MAX_LENGTH_ATTRIBUTE` rather than `ContextHandler.MAX_FORM_CONTENT_SIZE_KEY`.
To prepare ourselves for the transition, simplest just to inline the string so that we aren't depending on any particular calling convention.
`mvn clean install -DskipTests`
=> Inline `ContextHandler.MAX_FORM_CONTENT_SIZE_KEY`

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java
This code wasn't actually necessary, as demonstrated by the fact that the new test passes both with and without the changes to `src/main`. And since it would otherwise need to change for Jetty 12, simplest to delete it rather than adapt it for Jetty 12. This PR begins the process by deprecating it and removing consumption from this repository. A GitHub code search shows that there are a handful of consumers that aren't doing anything interesting. I will file some PRs to adapt the ones in `jenkinsci/`.
New test passes both with and without the changes to `src/main`.
=> Deprecate `MIME_TYPES`

src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Jetty 12 has removed the `Server#getChildHandlerByClass` method, but with some simple refactoring we can avoid having to call this method by returning a different object type, and this refactoring can be merged today on Jetty 10. Even though this looks like it's changing a public API, it's really not, since it begins with an underscore and is only used elsewhere in the test harness, and it's only public to be accessible by a different package.
`mvn clean verify -DskipTests`
=> Avoid usage of `Server#getChildHandlerByClass`

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
The last significant usage of this is in https://github.com/jenkinsci/kubernetes-pipeline-plugin/pull/97, but that plugin seems to be abandoned. Either way, a PR exists, so if and when that plugin is brought back to life, it should be easy to adapt to this removal.
`mvn clean verify`
=> [JENKINS-73124] Remove `MIME_TYPES`

pom.xml, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/QueryUtils.java
Updates the search method to support the 'Command palette' introduced n https://github.com/jenkinsci/jenkins/pull/7569. Also includes backwards compatibility for the classic YUI search bar.
=> Update search function for Command palette

pom.xml, src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java, src/main/java/org/jvnet/hudson/test/ComputerConnectorTester.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy2.java, src/main/java/org/jvnet/hudson/test/JenkinsComputerConnectorTester.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/MockFolder.java, src/main/java/org/jvnet/hudson/test/NoListenerConfiguration2.java, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/main/java/org/jvnet/hudson/test/UnitTestSupportingPluginManager.java, src/spotbugs/excludesFilter.xml
We plan to eventually migrate from Jetty 12 EE 8 to Jetty 12 EE 9, but the test harness only supports cores with Jetty 12 EE 8.
Bundle both the Jetty 12 EE 8 and EE 9 modules into the test harness, and dynamically select the module to load at runtime based on the Jenkins core in use.
This change does not increase the minimum core version supported by the test harness. To detect newer cores with EE 9 support and invoke the appropriate methods, reflection is used.
This plugin finds any places where we invoked EE 8 functionality in Jenkins core and turns them into an `if` statement. The existing code is in the `else` block, and the `if` block contains new code that invokes the relevant EE 9 functionality through reflection.
`JavaNetReverseProxy2` and `NoListenerConfiguration2` classes have …
=> [JENKINS-73260] Forward compatibility with EE 9 cores

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
As of jenkinsci/jenkins#9379, core doesn't do compression anymore. In production, Winstone enables compression, but in test scenarios, the test harness does not. This creates an unrealistic test environment.
Enable compression at the servlet container level in the test harness, matching production.
This change is not necessarily safe to backport, since on older cores it might result in double-compression. But it is safe to land on the default branch, since the `jenkins.version` is 2.463, which includes jenkinsci/jenkins#9379.
Will run PCT.
=> Delegate compression to servlet container

pom.xml
Backports #790 to the 2225.x (Java 11) branch.
The upgrade seems to be working fine on Jenkins core (on both the Jetty 12 EE 8 and EE 9 branches).
=> Backport "Bump org.jenkins-ci.main:jenkins-test-harness-htmlunit from 182.v85fe4a_4ee4f0 to 183.v9742e5ca_c784"

pom.xml
As of recent revisions of this patch set, I have moved EE 8 compatibility logic out of the EE 8 classes themselves and (back) into Stapler, so this code can be simplified.
=> Unfork EE 8 servlet API

pom.xml
Might as well keep this branch current as long as it is still getting updates.
Winstone tests for 10.0.22 passed already.
=> Update Jetty from 10.0.21 to 10.0.22 on Java 11 branch

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
`Options` does not qualify because its fields are mutable.
=> Make `InboundAgentRule.AgentArguments` into a `record`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
For some purposes in CloudBees CI it is necessary to run multiple agent processes with the same `-name`. This was not possible because `InboundAgentRule.start` presumed that the `Options.name` was in fact the URL component of the deprecated `-jnlpUrl`, and also treated `Options.name` as a unique key for purposes of process management.
=> Decouple `InboundAgentRule.Options.name` from `-jnlpUrl`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
Sometimes it is useful to be able to specify `-Dkey=value` or other options when launching the agent.
=> `javaOptions` for `InboundAgentRule`

pom.xml, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleFIPSTest.java
=> [JEP-237] Add new method to RealJenkinsRule to start in FIPS mode

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Unlike the situation in #512, this call was a no-op after the first step, yet [the implementation](https://github.com/jenkinsci/jenkins/blob/3767f78ae32b0170089d3537039d31f89a6441c9/core/src/main/java/jenkins/model/Jenkins.java#L1475) still saved `$JENKINS_HOME/config.xml`, causing churn and noise. (Extracted from #827.)
=> Avoid calling `Jenkins.setNoUsageStatistics` unless necessary

Jenkinsfile
https://ci.jenkins.io/job/Core/job/jenkins-test-harness/job/PR-837/1/ took 12m vs. https://ci.jenkins.io/job/Core/job/jenkins-test-harness/job/master/764/ 24m. If you just measure the `mvn` commands, so setting aside build queue time and so forth, 4.5m Linux / 9m Win vs. previous 8.5m / 19m. Either way, seems to make CI roughly twice as fast.
=> Try using `forkCount`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Amending #613 due to apparent flake in #838 https://github.com/jenkinsci/jenkins-test-harness/pull/838/checks?check_run_id=30338002288
```
java.net.SocketException: Connection reset
```
=> Generalize catch to `SocketException`

src/main/java/org/jvnet/hudson/test/TailLog.java
The symptom of #835 is a test case hanging _forever_, despite other timeouts such as in `RealJenkinsRule`. `waitForCompletion` is designed just to capture any final log output after a test has already asserted build completion with status, so it should time out. (Extracted from #827.)
=> Do not let `TailLog.waitForCompletion` block forever

src/main/java/org/jvnet/hudson/test/TailLog.java, src/test/java/org/jvnet/hudson/test/TailLogTest.java
I have some `RealJenkinsRule` tests which involve recreation of the build `log` file, but the default implementation of `Tailer` seems to be bound to an open file handle and thus does not notice any new content. Opening the file each time is of course less efficient but this utility is typically used only on very small log files in otherwise expensive tests so it should not matter. (Extracted from #827.)
=> `TailLog` to support reopened files

src/main/java/org/jvnet/hudson/test/recipes/WithPluginManager.java
Reverting https://github.com/jenkinsci/jenkins-test-harness/pull/838#discussion_r1765579500 as it seems to cause a regression I do not understand in `hudson.PluginManagerTest.uberClassLoaderIsAvailableDuringStart`. The nature of the `rootDir` parameter passed reflectively is undocumented generally, but `LocalPluginManager` expects it to be `$JENKINS_HOME` not `$JENKINS_HOME/plugins`.
=> Revert `WithPluginManager` constructor behavior

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
https://github.com/jenkinsci/jenkins-test-harness/pull/838#discussion_r1768928055
=> `InboundAgentRule` should use a temp file for `agent.jar`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
I noticed some flakes in a CloudBees CI test which just showed Jenkins failing to terminate within 60s, for no clear reason. I think what was happening was that `Jenkins.doQuietDown` was hanging, presumably because something was still running and would not quit; `stopJenkins` was probably being called in response to some test failure, but whatever that was, it was lost. I think `stopJenkins` ought to consistently shut down the controller cleanly and cap the amount of time it will wait for “quiet down” to complete. Note that this quiet down behavior seems to have been introduced in #281 and was then only temporarily suppressed in #544.
Test before fix:
```
…
2024-09-26 18:20:04.696+0000 [id=164]	WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class …
```
=> `doSafeExit` from `RealJenkinsRule` could hang

pom.xml
Reverts jenkinsci/jenkins-test-harness#844
Currently stumped by a JTH release failure. https://github.com/jenkinsci/jenkins-test-harness/actions/runs/11060243118/job/30730386885 complains about missing `org.jenkins-ci.main:jenkins-war:executable-war:2.476`. Indeed https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.476/ only has `jenkins-war-2.476.war` but that is by design; https://github.com/jenkinsci/maven-hpi-plugin/pull/65 + https://github.com/jenkinsci/jenkins-test-harness/pull/61 are supposed to look up the `*.war` and just add it to the Java classpath. https://github.com/jenkinsci/jenkins-test-harness/actions/runs/10966208526/job/30453668284 worked normally just a few days ago (using the same versions of Maven and Java), and the only POM change since then is …
=> Revert "Bump org.jenkins-ci:jenkins from 1.122 to 1.123"

RealJenkinsRuleInit/src/main/resources/index.jelly
=> Deleting orphaned `index.jelly` from `RealJenkinsRuleInit`

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Gracefully deal with the case where `DEBUG_YUI` is not defined in core.
Ran a test successfully both with and without `DEBUG_YUI` defined in core.
=> Tolerate missing `DEBUG_YUI` field

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
I need to simulate a hard shutdown, without executing the usual Jenkins clean up sequence.
=> Add a new method to force shutdown a RealJenkinsRule instance

src/main/java/jenkins/test/RunMatchers.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/jenkins/test/RunMatchersTest.java
Plays nicely with Awaitability as well as in combination with other matchers.
=> Provide Hamcrest matchers as alternatives to built-in JenkinsRule run assertions

pom.xml, src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/main/java/org/jvnet/hudson/test/XStreamSerializable.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
Occasionally a `RealJenkinsRule`-based test utility needs to pass and/or return a structured object which is not `Serializable`. This is currently awkward; you can try to move the code to create/assert the object inside the Jenkins JVM, or find some ad-hoc way of passing it. Since XStream does not require objects to implement `Serializable`, and many types used in Jenkins are safe to round-trip via XML but are not marked `Serializable`, it is convenient to be able to work with them directly. (I considered just relaxing the signatures of the various `runRemotely` overloads to tolerate any `Object`, and magically wrap them if not already `Serializable`, but this seemed complicated and prone to abuse. It is better to be conscious of the fact that you are serializing objects _somehow_.)
=> `XStreamSerializable`

src/main/java/jenkins/model/JenkinsAdaptor.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Was apparently necessary as of https://github.com/jenkinsci/jenkins/pull/152 but was superseded a few weeks later by https://github.com/jenkinsci/jenkins/commit/f350227c25edf1d3682ffa2030a2f1e37431a1e6.
=> Deprecating `JenkinsRule.setQuietPeriod`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleSyntheticPluginTest.java, src/test/java/org/jvnet/hudson/test/sample/plugin/CustomJobProperty.java
A bug I found in #659: https://jenkins.io/jep/200 did not whitelist synthetic plugins, because it expected the actual classes JAR (unpacked from inside the `*.jpi`) to include a valid plugin manifest. `maven-hpi-plugin` uses the same manifest for both, so I am following suit.
=> `SyntheticPlugin` neglected to include manifest in classes JAR

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
This will allow Jenkins to leverage `web-fragment.xml` and Servlet 3.0 annotations.
[JENKINS-75174](https://issues.jenkins.io/browse/JENKINS-75174)
Downstream change
* https://github.com/jenkinsci/jenkins/pull/10185
Checked that JenkinsRule-based tests still run as expected, and are able to pick up web fragments when defined and allowed by web.xml (e.g. `metadata-complete="false"` or missing)
=> [JENKINS-75174] Allow webapp context configuration to be discovered via Servlet 3.0 discovery

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Backporting #905 to the last version before dropping ee8.
=> [JENKINS-75174] Web fragments support

src/main/java/org/jvnet/hudson/test/recipes/LocalData.java, src/test/java/org/jvnet/hudson/test/recipes/LocalDataExtendedTest.java
By switching to `getDeclaredMethod` in #900, this broke this use case that is currently exercised in email-ext plugin
(`ScriptContentSecureTest>ScriptContentTest#testTemplateShouldBeLoadedFromTheClosestExistingFolderConfigInTheHierarchyUpToGlobalConfig`)
The provided test breaks without this patch.
=> Fixes `@LocalData` when being used on a test method in superclass

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/main/java/org/jvnet/hudson/test/TailLog.java
The `junit` plugin displays stdout & stderr separately, following the separated streams in Surefire `TEST-*.xml`. This is just confusing when you are trying to see the sequence of events: you need to mentally collate by timestamp to reconstruct the log you would see from `mvn test -Dtest=…` output (compare https://github.com/jenkinsci/plugin-pom/blob/8561e2e8c77c344d0465ec6c77e2e3eedc927c00/pom.xml#L1070-L1080) particularly if the output includes a mixture of `Logger` lines from the Surefire JVM and the Jenkins JVM.
=> Use stderr rather than stdout for `RealJenkinsRule` & `TailLog`

src/main/java/org/jvnet/hudson/test/junit/jupiter/JUnit5JenkinsRule.java, src/test/java/org/jvnet/hudson/test/JenkinsRulePermissionTest.java
Fixes #901
This PR raises the default permissions of `JUnit5JenkinsRule` to align with their JUnit4 counterparts.
It is important to notice that this change is breaking and will cause _some_ JUnit5 based plugin tests to fail in case they rely on the fact that the default user / permission is `Unauthenticated`.
The alternative would be to leave the permissions as they are but make users aware of the differences in JUnit4 and JUnit5.
JUnit5 based tests may fail due to this change (as they expect to run in an `Unauthenticated` context) - like for example:
```java
@Test
void testUnauthenticated(JenkinsRule r) throws Exception {
DummySecurityRealm realm = r.createDummySecurityRealm();
r.jenkins.setSecurityRealm(realm);
MockAuthorizationStrategy strategy = new MockAuthorizationStrategy(); …
```
=> Raise default permissions of `JUnit5JenkinsRule`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
=> Add `RealJenkinsRule.run` / `.call` aliases

src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy2.java
In Jenkins core builds, we see frequent flakiness in `hudson.PluginManagerTest#doNotThrowWithUnknownPlugins`. Right before the test fails we see:
```
4.236 [id=64]	WARNING	o.e.jetty.ee9.nested.HttpChannel#handleException: handleException /update-center.json java.nio.file.NoSuchFileException: /home/jenkins/agent/workspace/Core_jenkins_PR-10231/test/target/jenkins.io-cache2/a99c432e44df4790e1a50308de383c6d
```
`JavaNetReverseProxy2` has concurrency issues when multiple processes are being used, which is the case in our CI builds which both set `forkCount=2` and `reuseForks=false`. This results in two separate JVMs running concurrently executing test cases.
This class was designed for a single JVM to be in use at any time, for a few reasons. First, it has a fixed name for the cache …
=> Revisit concurrency in `JavaNetReverseProxy2#service`

src/main/java/org/jvnet/hudson/test/JenkinsSessionRule.java, src/main/java/org/jvnet/hudson/test/RestartableJenkinsRule.java
I found that some plugin developers were unaware that this class had long since been superseded by `JenkinsSessionRule`.
=> Deprecating `RestartableJenkinsRule`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java, src/test/java/org/jvnet/hudson/test/RealJenkinsRuleTest.java
=> Add support for custom prefix

pom.xml, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
=> [JENKINS-75278] Upgrade Jetty 12.0.17 which restore UriCompliance.LEGACY previous behaviour

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
This field is deprecated as of https://github.com/jenkinsci/jenkins/pull/8762. When using Jenkins, the UI never sets it to `true`
=> Websocket field on `JNLPLauncher` is deprecated

src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/test/java/org/jvnet/hudson/test/JenkinsRuleTest.java, src/test/java/org/jvnet/hudson/test/junit/jupiter/JUnit5JenkinsRuleTest.java
My initial implementation of `JenkinsRule#restart` in https://github.com/jenkinsci/jenkins-test-harness/pull/716 seems to be flawed in a sense that the underlying Jenkins instance is restored with a copy of the original `JENKINS_HOME` under a *new* path.
In https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/302 in became clear that this impacts some corner cases where this path is actually relevant for some plugins (see https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/302#issuecomment-2718877688).
This PR aims to remove this flaw. Now `JenkinsRule#restart` will start a new instance with a copy of the original `JENKINS_HOME` under the *same* path as the previous instance. This is achieved by creating a `backup.zip` from the current `JENKINS_HOME` before …
=> `JenkinsRule#restart` preserves the original root path

src/main/java/org/jvnet/hudson/test/NoListenerConfiguration2.java
Extracted from #941, as this change can be merged and released proactively. Today we hard-code EE 9 in `NoListenerConfiguration2` by importing `org.eclipse.jetty.ee9.webapp.WebAppContext`, making it difficult to support both EE 9 and EE 10 in the future as we would like to do in #941. By choosing the type `AbstractLifeCycle` (a common superclass of both `org.eclipse.jetty.ee9.webapp.WebAppContext` and `org.eclipse.jetty.ee10.webapp.WebAppContext` that still has the methods we need), we make this class agnostic to EE version and ease future maintenance.
CI build. Also tested in the context of #941 with both EE 9 and EE 10 cores in a plugin's test suite.
=> Make `NoListenerConfiguration2` agnostic to EE version

src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java
Extracted from https://github.com/jenkinsci/jenkins-test-harness/pull/941, as this change can be merged and released proactively. The `setResourceBase` method has been deprecated in favor of `setBaseResource`, and `setResourceBase` has been removed entirely in EE 10. So migrate to the new functionality proactively so that the code continues to compile in the future when we are on EE 10.
CI build, as well as testing `hpi:run` on an EE 10 core in a plugin as part of #941.
=> Reduce usage of deprecated Jetty methods

src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy2.java
Extracted from #941, as this change can be merged and released proactively. Simplify our usage by removing `ContextHandlerCollection`, which isn't needed and works differently in EE 10. The simpler version of the code works fine in EE 9 and EE 10.
Stepped through the servlet code in both EE 9 and EE 10 to make sure it functions as before without regression.
=> Simplify `JavaNetReverseProxy2`

pom.xml, src/main/java/jenkins/benchmark/jmh/JmhBenchmarkState.java, src/main/java/org/jvnet/hudson/test/HudsonTestCase.java, src/main/java/org/jvnet/hudson/test/JavaNetReverseProxy2.java, src/main/java/org/jvnet/hudson/test/JenkinsRule.java, src/main/java/org/jvnet/hudson/test/jetty/Jetty12EE10Provider.java, src/main/java/org/jvnet/hudson/test/jetty/Jetty12EE9Provider.java, src/main/java/org/jvnet/hudson/test/jetty/JettyProvider.java
Part of the following series of PRs:
- https://github.com/jenkinsci/jelly/pull/140
- https://github.com/jenkinsci/stapler/pull/617
- https://github.com/jenkinsci/winstone/pull/422
- https://github.com/jenkinsci/jenkins/pull/10461
- https://github.com/jenkinsci/jenkins-test-harness/pull/941
The test harness only supports EE 9, precluding an eventual upgrade to EE 10.
Support both EE 9 and EE 10 in the test harness, dynamically selecting the version of Jakarta EE based on the Jenkins core under test. This is similar at a high level to a previous PR that added support for both EE 8 and EE 9, though the details are different: in this case, the same `jakarta.servlet` types are in use, and the implementation is much cleaner.
Normally, the test harness is consumed in the plugin parent POM, which …
=> [JENKINS-75572] Add support for Jakarta EE 10

src/main/java/org/jvnet/hudson/test/JenkinsRule.java
https://github.com/jenkinsci/jenkins/pull/10654#issuecomment-2891852932 I have no evidence this helps aything, but noticed from code inspection (related to #922) that this method is launching as asynch process and then neglecting to wait for it, which is usually a bad practice in test code.
=> `JenkinsRule.disconnectSlave` should wait for `SlaveComputer.disconnectSlave`

src/main/java/org/jvnet/hudson/test/RealJenkinsRule.java
Found to be useful in some tests in CloudBees CI.
=> `RealJenkinsRule.run(ErrorCollector, Step)`

src/main/java/org/jvnet/hudson/test/InboundAgentRule.java
The main impact is `InboundAgentRule#startOnly(RealJenkinsRule, Options)`.
This is used for test scenarios reproducing issues of extra processes claiming to be the same agent.
=> Support starting multiple instance of the same agent.

src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
No need to depend on a third-party library here when the Java Platform would suffice.
=> Remove `StringUtils` from test harness
